// words-data.js
// =====================
// 词库数据
// =====================

window.UNITS = [
    {
        id: 1,
        name: "New Words 1",
        words: [
            { hanzi: "免贵", pinyin: "miǎn guì", meaning: "a polite response when asked one's surname" },
            { hanzi: "副总", pinyin: "fù zǒng", meaning: "deputy general manager" },
            { hanzi: "董事长", pinyin: "dǒng shì zhǎng", meaning: "chairman of the board" },
            { hanzi: "全家", pinyin: "quán jiā", meaning: "the whole family" },
            { hanzi: "称呼", pinyin: "chēng hu", meaning: "address (a person)" },
            { hanzi: "先生", pinyin: "xiān sheng", meaning: "Mr. / sir" },
            { hanzi: "哪位", pinyin: "nǎ wèi", meaning: "which person (polite)" },
            { hanzi: "司机", pinyin: "sī jī", meaning: "driver" },
            { hanzi: "师傅", pinyin: "shī fu", meaning: "master (respectful title)" },
            { hanzi: "阿姨", pinyin: "ā yí", meaning: "aunt" },
            { hanzi: "保姆", pinyin: "bǎo mǔ", meaning: "nanny" },
            { hanzi: "黑屏", pinyin: "hēi píng", meaning: "black screen" },
            { hanzi: "分享屏幕", pinyin: "fēn xiǎng píng mù", meaning: "share the screen" },
            { hanzi: "声音", pinyin: "shēng yīn", meaning: "sound / voice" },
            { hanzi: "称重", pinyin: "chēng zhòng", meaning: "weigh" },
            { hanzi: "秤", pinyin: "chèng", meaning: "scale" },
            { hanzi: "开会", pinyin: "kāi huì", meaning: "have a meeting" },
            { hanzi: "介绍", pinyin: "jiè shào", meaning: "introduce" },
            { hanzi: "认识", pinyin: "rèn shi", meaning: "know (someone)" },
            { hanzi: "菜市场", pinyin: "cài shì chǎng", meaning: "vegetable market" },
            { hanzi: "市场部", pinyin: "shì chǎng bù", meaning: "marketing department" },
            { hanzi: "去过", pinyin: "qù guò", meaning: "have been to (a place)" },
            { hanzi: "放假", pinyin: "fàng jià", meaning: "have a holiday / take a vacation" },
            { hanzi: "请假", pinyin: "qǐng jià", meaning: "ask for leave" },
            { hanzi: "春节", pinyin: "chūn jié", meaning: "Spring Festival" },
            { hanzi: "圣诞节", pinyin: "shèng dàn jié", meaning: "Christmas" },
            { hanzi: "翻译", pinyin: "fān yì", meaning: "translate / translation" },
            { hanzi: "陪", pinyin: "péi", meaning: "accompany" },
            { hanzi: "是这样", pinyin: "shì zhè yàng", meaning: "it's like this / that's the case" },
            { hanzi: "月末", pinyin: "yuè mò", meaning: "the end of the month" },
            { hanzi: "周末", pinyin: "zhōu mò", meaning: "weekend" },
            { hanzi: "展览馆", pinyin: "zhǎn lǎn guǎn", meaning: "exhibition hall" },
            { hanzi: "游览", pinyin: "yóu lǎn", meaning: "visit / tour" },
            { hanzi: "不错", pinyin: "bù cuò", meaning: "not bad / good" },
            { hanzi: "没错", pinyin: "méi cuò", meaning: "that's right / correct" },
            { hanzi: "自信", pinyin: "zì xìn", meaning: "self-confident" },
            { hanzi: "好像", pinyin: "hǎo xiàng", meaning: "seem / look like" },
            { hanzi: "待多久", pinyin: "dài duō jiǔ", meaning: "how long to stay" },
            { hanzi: "时间", pinyin: "shí jiān", meaning: "time" },
            { hanzi: "时候", pinyin: "shí hou", meaning: "time (when something happens)" },
            { hanzi: "整天", pinyin: "zhěng tiān", meaning: "the whole day" },
            { hanzi: "整点", pinyin: "zhěng diǎn", meaning: "on the hour" },
            { hanzi: "听说", pinyin: "tīng shuō", meaning: "hear of / be told" },
            { hanzi: "出国", pinyin: "chū guó", meaning: "go abroad" },
            { hanzi: "回国", pinyin: "huí guó", meaning: "return to one's country" },
            { hanzi: "半天", pinyin: "bàn tiān", meaning: "half a day" },
            { hanzi: "也就是说", pinyin: "yě jiù shì shuō", meaning: "that is to say / in other words" },
            { hanzi: "厂长", pinyin: "chǎng zhǎng", meaning: "factory director" },
            { hanzi: "长大", pinyin: "zhǎng dà", meaning: "grow up" },
            { hanzi: "上班", pinyin: "shàng bān", meaning: "go to work" },
            { hanzi: "下班", pinyin: "xià bān", meaning: "get off work" },
            { hanzi: "上学", pinyin: "shàng xué", meaning: "go to school" },
            { hanzi: "上课", pinyin: "shàng kè", meaning: "have a class" },
            { hanzi: "下课", pinyin: "xià kè", meaning: "finish class" },
            { hanzi: "上月", pinyin: "shàng yuè", meaning: "last month" },
            { hanzi: "下月", pinyin: "xià yuè", meaning: "next month" },
            { hanzi: "上月末", pinyin: "shàng yuè mò", meaning: "the end of last month" },
            { hanzi: "下月末", pinyin: "xià yuè mò", meaning: "the end of next month" },
            { hanzi: "上上月", pinyin: "shàng shàng yuè", meaning: "the month before last" },
            { hanzi: "下下月", pinyin: "xià xià yuè", meaning: "the month after next" },
            { hanzi: "有课", pinyin: "yǒu kè", meaning: "have a class" },
            { hanzi: "说错了", pinyin: "shuō cuò le", meaning: "said something wrong" },
            { hanzi: "打错了", pinyin: "dǎ cuò le", meaning: "typed / dialed wrong" },
            { hanzi: "汉语", pinyin: "hàn yǔ", meaning: "Chinese language" },
            { hanzi: "短视频", pinyin: "duǎn shì pín", meaning: "short video" },
            { hanzi: "放短视频", pinyin: "fàng duǎn shì pín", meaning: "play a short video" },
            { hanzi: "通过一下", pinyin: "tōng guò yí xià", meaning: "let sb. pass / approve" },
            { hanzi: "微信", pinyin: "Wēi xìn", meaning: "WeChat" },
            { hanzi: "扫码付款", pinyin: "sǎo mǎ fù kuǎn", meaning: "scan the code to pay" },
            { hanzi: "小费", pinyin: "xiǎo fèi", meaning: "tip" },
            { hanzi: "免费", pinyin: "miǎn fèi", meaning: "free of charge" },
            { hanzi: "参观工厂", pinyin: "cān guān gōng chǎng", meaning: "visit the factory" },
            { hanzi: "公司", pinyin: "gōng sī", meaning: "company" },
            { hanzi: "办公室", pinyin: "bàn gōng shì", meaning: "office" },
            { hanzi: "进步", pinyin: "jìn bù", meaning: "progress" },
            { hanzi: "惊喜", pinyin: "jīng xǐ", meaning: "surprise" },
            { hanzi: "贵宾", pinyin: "guì bīn", meaning: "VIP" },
            { hanzi: "向左转", pinyin: "xiàng zuǒ zhuǎn", meaning: "turn left" },
            { hanzi: "直走", pinyin: "zhí zǒu", meaning: "go straight" },
            { hanzi: "直飞", pinyin: "zhí fēi", meaning: "direct flight" },
            { hanzi: "转机", pinyin: "zhuǎn jī", meaning: "connecting flight" },
            { hanzi: "一直", pinyin: "yì zhí", meaning: "always / all the time" },
            { hanzi: "接电话", pinyin: "jiē diàn huà", meaning: "answer the phone" },
            { hanzi: "关机", pinyin: "guān jī", meaning: "turn off a device" },
            { hanzi: "开机", pinyin: "kāi jī", meaning: "turn on a device" },
            { hanzi: "没电", pinyin: "méi diàn", meaning: "out of power / dead battery" },
            { hanzi: "打不通", pinyin: "dǎ bù tōng", meaning: "can't get through (on the phone)" },
            { hanzi: "占线", pinyin: "zhàn xiàn", meaning: "the line is busy" },
            { hanzi: "联系", pinyin: "lián xì", meaning: "contact" },
            { hanzi: "练习", pinyin: "liàn xí", meaning: "practice / exercise" },
            { hanzi: "高跟鞋", pinyin: "gāo gēn xié", meaning: "high-heeled shoes" },
            { hanzi: "忙线", pinyin: "máng xiàn", meaning: "the line is busy" },
            { hanzi: "过几分钟", pinyin: "guò jǐ fēn zhōng", meaning: "call again in a few minutes" },
            { hanzi: "打通了吗", pinyin: "dǎ tōng le ma", meaning: "did you get through?" },
            { hanzi: "通了", pinyin: "tōng le", meaning: "got through" },
            { hanzi: "过几天再说", pinyin: "guò jǐ tiān zài shuō", meaning: "discuss it in a few days" },
            { hanzi: "没打通", pinyin: "méi dǎ tōng", meaning: "didn't get through" },
            { hanzi: "好久没联系了", pinyin: "hǎo jiǔ méi lián xì le", meaning: "haven't been in touch for a long time" },
            { hanzi: "关系", pinyin: "guān xì", meaning: "relationship / relation" },
            { hanzi: "留言", pinyin: "liú yán", meaning: "leave a message" },
            { hanzi: "邮箱", pinyin: "yóu xiāng", meaning: "email address / mailbox" },
            { hanzi: "发邮件", pinyin: "fā yóu jiàn", meaning: "send an email" },
            { hanzi: "箱子", pinyin: "xiāng zi", meaning: "box / suitcase" },
            { hanzi: "冰箱", pinyin: "bīng xiāng", meaning: "refrigerator / fridge" },
            { hanzi: "常联系", pinyin: "cháng lián xì", meaning: "keep in touch often" },
            { hanzi: "联系方式", pinyin: "lián xì fāng shì", meaning: "contact information" },
            { hanzi: "支付方式", pinyin: "zhī fù fāng shì", meaning: "payment method" },
            { hanzi: "支付宝", pinyin: "Zhī fù bǎo", meaning: "Alipay" },
            { hanzi: "请教", pinyin: "qǐng jiào", meaning: "ask for advice" },
            { hanzi: "业务", pinyin: "yè wù", meaning: "business" },
            { hanzi: "语言", pinyin: "yǔ yán", meaning: "language" },
            { hanzi: "网购", pinyin: "wǎng gòu", meaning: "online shopping" },
            { hanzi: "上网", pinyin: "shàng wǎng", meaning: "surf the Internet / go online" },
            { hanzi: "方便", pinyin: "fāng biàn", meaning: "convenient" }
        ]
    },
    {
        id: 2,
        name: "New Words 2",
        words: [
            { hanzi: "网络", pinyin: "wǎng luò", meaning: "network" },
            { hanzi: "网址", pinyin: "wǎng zhǐ", meaning: "website address" },
            { hanzi: "网站", pinyin: "wǎng zhàn", meaning: "website" },
            { hanzi: "网页", pinyin: "wǎng yè", meaning: "webpage" },
            { hanzi: "上网", pinyin: "shàng wǎng", meaning: "surf the Internet" },
            { hanzi: "网购", pinyin: "wǎng gòu", meaning: "online shopping" },
            { hanzi: "信号", pinyin: "xìn hào", meaning: "signal" },
            { hanzi: "掉线", pinyin: "diào xiàn", meaning: "drop the line / disconnect" },
            { hanzi: "密码", pinyin: "mì mǎ", meaning: "password" },
            { hanzi: "聊天", pinyin: "liáo tiān", meaning: "chat" },
            { hanzi: "收费", pinyin: "shōu fèi", meaning: "charge" },
            { hanzi: "免费", pinyin: "miǎn fèi", meaning: "free of charge" },
            { hanzi: "在线", pinyin: "zài xiàn", meaning: "online" },
            { hanzi: "线上", pinyin: "xiàn shàng", meaning: "online" },
            { hanzi: "线下", pinyin: "xiàn xià", meaning: "offline" },
            { hanzi: "下线", pinyin: "xià xiàn", meaning: "go offline" },
            { hanzi: "转弯", pinyin: "zhuǎn wān", meaning: "turn" },
            { hanzi: "后备箱", pinyin: "hòu bèi xiāng", meaning: "trunk (of a car)" },
            { hanzi: "马上", pinyin: "mǎ shàng", meaning: "immediately" },
            { hanzi: "火车", pinyin: "huǒ chē", meaning: "train" },
            { hanzi: "红绿灯", pinyin: "hóng lǜ dēng", meaning: "traffic light" },
            { hanzi: "一辆车", pinyin: "yí liàng chē", meaning: "a car" },
            { hanzi: "一台车", pinyin: "yì tái chē", meaning: "a car" },
            { hanzi: "赶时间", pinyin: "gǎn shí jiān", meaning: "be in a hurry" },
            { hanzi: "赶飞机", pinyin: "gǎn fēi jī", meaning: "catch a plane" },
            { hanzi: "赶忙", pinyin: "gǎn máng", meaning: "hurry" },
            { hanzi: "赶快", pinyin: "gǎn kuài", meaning: "hurry up" },
            { hanzi: "去年", pinyin: "qù nián", meaning: "last year" },
            { hanzi: "明年", pinyin: "míng nián", meaning: "next year" },
            { hanzi: "上周", pinyin: "shàng zhōu", meaning: "last week" },
            { hanzi: "下周", pinyin: "xià zhōu", meaning: "next week" },
            { hanzi: "上月", pinyin: "shàng yuè", meaning: "last month" },
            { hanzi: "下月", pinyin: "xià yuè", meaning: "next month" },
            { hanzi: "数字", pinyin: "shù zì", meaning: "number" },
            { hanzi: "数一数", pinyin: "shǔ yì shǔ", meaning: "count" },
            { hanzi: "筷子", pinyin: "kuài zi", meaning: "chopsticks" },
            { hanzi: "一双筷子", pinyin: "yì shuāng kuài zi", meaning: "a pair of chopsticks" },
            { hanzi: "乘客", pinyin: "chéng kè", meaning: "passenger" },
            { hanzi: "乘务员", pinyin: "chéng wù yuán", meaning: "flight attendant / conductor" },
            { hanzi: "尾号", pinyin: "wěi hào", meaning: "last digit (of a number)" },
            { hanzi: "麻烦", pinyin: "má fan", meaning: "trouble / inconvenience" },
            { hanzi: "系安全带", pinyin: "jì ān quán dài", meaning: "fasten the seat belt" },
            { hanzi: "鞋带", pinyin: "xié dài", meaning: "shoelace" },
            { hanzi: "出发", pinyin: "chū fā", meaning: "depart" },
            { hanzi: "快下雨了", pinyin: "kuài xià yǔ le", meaning: "it's going to rain soon" },
            { hanzi: "快点", pinyin: "kuài diǎn", meaning: "hurry up" },
            { hanzi: "快乐", pinyin: "kuài lè", meaning: "happy" },
            { hanzi: "省钱", pinyin: "shěng qián", meaning: "save money" },
            { hanzi: "花钱", pinyin: "huā qián", meaning: "spend money" },
            { hanzi: "空调", pinyin: "kōng tiáo", meaning: "air conditioner" },
            { hanzi: "调高点", pinyin: "tiáo gāo diǎn", meaning: "turn up (the temperature)" },
            { hanzi: "调低点", pinyin: "tiáo dī diǎn", meaning: "turn down (the temperature)" },
            { hanzi: "靠边停", pinyin: "kào biān tíng", meaning: "pull over" },
            { hanzi: "靠窗", pinyin: "kào chuāng", meaning: "by the window" },
            { hanzi: "靠走道", pinyin: "kào zǒu dào", meaning: "by the aisle" },
            { hanzi: "靠我自己", pinyin: "kào wǒ zì jǐ", meaning: "depend on myself" },
            { hanzi: "目的", pinyin: "mù dì", meaning: "purpose" },
            { hanzi: "目的地", pinyin: "mù dì dì", meaning: "destination" },
            { hanzi: "现金", pinyin: "xiàn jīn", meaning: "cash" },
            { hanzi: "美金", pinyin: "měi jīn", meaning: "US dollar" },
            { hanzi: "美元", pinyin: "měi yuán", meaning: "US dollar" },
            { hanzi: "两天后", pinyin: "liǎng tiān hòu", meaning: "two days later" },
            { hanzi: "后天", pinyin: "hòu tiān", meaning: "the day after tomorrow" },
            { hanzi: "随身物品", pinyin: "suí shēn wù pǐn", meaning: "carry-on items" },
            { hanzi: "网约车", pinyin: "wǎng yuē chē", meaning: "ride-hailing car" },
            { hanzi: "约会", pinyin: "yuē huì", meaning: "date" },
            { hanzi: "约时间", pinyin: "yuē shí jiān", meaning: "make an appointment" },
            { hanzi: "无人驾驶", pinyin: "wú rén jià shǐ", meaning: "autonomous driving" },
            { hanzi: "萝卜快跑", pinyin: "luó bo kuài pǎo", meaning: "RoboSense / autonomous driving brand" },
            { hanzi: "驾驶", pinyin: "jià shǐ", meaning: "drive" },
            { hanzi: "驾照", pinyin: "jià zhào", meaning: "driver's license" },
            { hanzi: "输入", pinyin: "shū rù", meaning: "input" },
            { hanzi: "点击", pinyin: "diǎn jī", meaning: "click" },
            { hanzi: "开始行程", pinyin: "kāi shǐ xíng chéng", meaning: "start the trip" },
            { hanzi: "音乐响了", pinyin: "yīn yuè xiǎng le", meaning: "the music is playing" },
            { hanzi: "右侧", pinyin: "yòu cè", meaning: "right side" },
            { hanzi: "厕所", pinyin: "cè suǒ", meaning: "toilet" },
            { hanzi: "相伴", pinyin: "xiāng bàn", meaning: "accompany" },
            { hanzi: "期待", pinyin: "qī dài", meaning: "expect" },
            { hanzi: "付费", pinyin: "fù fèi", meaning: "pay for" },
            { hanzi: "商务汉语", pinyin: "shāng wù hàn yǔ", meaning: "business Chinese" },
            { hanzi: "生活汉语", pinyin: "shēng huó hàn yǔ", meaning: "daily Chinese" },
            { hanzi: "白说", pinyin: "bái shuō", meaning: "say in vain" },
            { hanzi: "白等", pinyin: "bái děng", meaning: "wait in vain" },
            { hanzi: "白学", pinyin: "bái xué", meaning: "study in vain" },
            { hanzi: "卖完了", pinyin: "mài wán le", meaning: "sold out" },
            { hanzi: "瞎说", pinyin: "xiā shuō", meaning: "talk nonsense" },
            { hanzi: "瞎忙", pinyin: "xiā máng", meaning: "be busy with nothing" },
            { hanzi: "办点事", pinyin: "bàn diǎn shì", meaning: "do some errands" },
            { hanzi: "买点东西", pinyin: "mǎi diǎn dōng xi", meaning: "buy some things" },
            { hanzi: "办公时间", pinyin: "bàn gōng shí jiān", meaning: "office hours" },
            { hanzi: "厂长", pinyin: "chǎng zhǎng", meaning: "factory director" },
            { hanzi: "家长", pinyin: "jiā zhǎng", meaning: "parent" },
            { hanzi: "校长", pinyin: "xiào zhǎng", meaning: "principal" },
            { hanzi: "园长", pinyin: "yuán zhǎng", meaning: "kindergarten principal" },
            { hanzi: "你干啥呢", pinyin: "nǐ gàn shá ne", meaning: "What are you doing?" },
            { hanzi: "最近怎么样", pinyin: "zuì jìn zěn me yàng", meaning: "How have you been lately?" },
            { hanzi: "老样子", pinyin: "lǎo yàng zi", meaning: "same as before" },
            { hanzi: "挺好的", pinyin: "tǐng hǎo de", meaning: "pretty good" },
            { hanzi: "还好", pinyin: "hái hǎo", meaning: "not bad" },
            { hanzi: "一般般", pinyin: "yì bān bān", meaning: "so-so" },
            { hanzi: "我得走了", pinyin: "wǒ děi zǒu le", meaning: "I have to go" },
            { hanzi: "样品", pinyin: "yàng pǐn", meaning: "sample" },
            { hanzi: "手机没电了", pinyin: "shǒu jī méi diàn le", meaning: "the phone is out of power" },
            { hanzi: "要充电了", pinyin: "yào chōng diàn le", meaning: "need to charge" },
            { hanzi: "销售", pinyin: "xiāo shòu", meaning: "sales" },
            { hanzi: "一般", pinyin: "yì bān", meaning: "ordinary" },
            { hanzi: "关心", pinyin: "guān xīn", meaning: "care about" },
            { hanzi: "今天或明天都可以", pinyin: "jīn tiān huò míng tiān dōu kě yǐ", meaning: "either today or tomorrow is fine" },
            { hanzi: "太", pinyin: "tài", meaning: "too / very" },
            { hanzi: "你怎么才来呀", pinyin: "nǐ zěn me cái lái ya", meaning: "Why did you come so late?" },
            { hanzi: "电梯", pinyin: "diàn tī", meaning: "elevator" },
            { hanzi: "领带", pinyin: "lǐng dài", meaning: "tie" },
            { hanzi: "太早了", pinyin: "tài zǎo le", meaning: "too early" },
            { hanzi: "商场没开门", pinyin: "shāng chǎng méi kāi mén", meaning: "the mall isn't open" },
            { hanzi: "我们改天吧", pinyin: "wǒ men gǎi tiān ba", meaning: "Let's make it another day" },
            { hanzi: "改时间", pinyin: "gǎi shí jiān", meaning: "change the time" },
            { hanzi: "写字楼", pinyin: "xiě zì lóu", meaning: "office building" },
            { hanzi: "外企", pinyin: "wài qǐ", meaning: "foreign-funded enterprise" },
            { hanzi: "离家不远", pinyin: "lí jiā bù yuǎn", meaning: "not far from home" },
            { hanzi: "堵车", pinyin: "dǔ chē", meaning: "traffic jam" },
            { hanzi: "移动", pinyin: "yí dòng", meaning: "mobile" },
            { hanzi: "移动WiFi", pinyin: "yí dòng WiFi", meaning: "portable WiFi" },
            { hanzi: "航班", pinyin: "háng bān", meaning: "flight" },
            { hanzi: "航站楼", pinyin: "háng zhàn lóu", meaning: "terminal" },
            { hanzi: "登机", pinyin: "dēng jī", meaning: "board the plane" },
            { hanzi: "登机口", pinyin: "dēng jī kǒu", meaning: "boarding gate" },
            { hanzi: "航空公司", pinyin: "háng kōng gōng sī", meaning: "airline company" },
            { hanzi: "旅行", pinyin: "lǚ xíng", meaning: "travel" },
            { hanzi: "祝你旅途愉快", pinyin: "zhù nǐ lǚ tú yú kuài", meaning: "Wish you a pleasant trip" },
            { hanzi: "周末愉快", pinyin: "zhōu mò yú kuài", meaning: "Happy weekend" },
            { hanzi: "牌子", pinyin: "pái zi", meaning: "brand" },
            { hanzi: "你喜欢什么牌子的鞋", pinyin: "nǐ xǐ huān shén me pái zi de xié", meaning: "What brand of shoes do you like?" },
            { hanzi: "名牌", pinyin: "míng pái", meaning: "famous brand" },
            { hanzi: "登机牌", pinyin: "dēng jī pái", meaning: "boarding pass" },
            { hanzi: "车牌", pinyin: "chē pái", meaning: "license plate" },
            { hanzi: "请出示护照", pinyin: "qǐng chū shì hù zhào", meaning: "Please show your passport" },
            { hanzi: "白班", pinyin: "bái bān", meaning: "day shift" },
            { hanzi: "晚班", pinyin: "wǎn bān", meaning: "night shift" },
            { hanzi: "白天", pinyin: "bái tiān", meaning: "daytime" },
            { hanzi: "晚上", pinyin: "wǎn shàng", meaning: "evening" },
            { hanzi: "事发地", pinyin: "shì fā dì", meaning: "scene of the incident" },
            { hanzi: "改", pinyin: "gǎi", meaning: "change" },
            { hanzi: "改变", pinyin: "gǎi biàn", meaning: "change" },
            { hanzi: "更换", pinyin: "gēng huàn", meaning: "replace" },
            { hanzi: "采购商", pinyin: "cǎi gòu shāng", meaning: "purchaser" },
            { hanzi: "报价", pinyin: "bào jià", meaning: "quote a price" },
            { hanzi: "报价单", pinyin: "bào jià dān", meaning: "quotation sheet" },
            { hanzi: "产品", pinyin: "chǎn pǐn", meaning: "product" },
            { hanzi: "生产", pinyin: "shēng chǎn", meaning: "produce" },
            { hanzi: "产房", pinyin: "chǎn fáng", meaning: "delivery room" },
            { hanzi: "产假", pinyin: "chǎn jià", meaning: "maternity leave" },
            { hanzi: "年假", pinyin: "nián jià", meaning: "annual leave" },
            { hanzi: "休假", pinyin: "xiū jià", meaning: "take a vacation" },
            { hanzi: "放假", pinyin: "fàng jià", meaning: "have a holiday" },
            { hanzi: "请假", pinyin: "qǐng jià", meaning: "ask for leave" },
            { hanzi: "买卖", pinyin: "mǎi mài", meaning: "buy and sell" },
            { hanzi: "款号", pinyin: "kuǎn hào", meaning: "style number" },
            { hanzi: "新款", pinyin: "xīn kuǎn", meaning: "new style" },
            { hanzi: "改变别人不如改变自己", pinyin: "gǎi biàn bié rén bù rú gǎi biàn zì jǐ", meaning: "It's better to change yourself than others" },
            { hanzi: "报价报错了", pinyin: "bào jià bào cuò le", meaning: "quoted the wrong price" },
            { hanzi: "改一下报价单", pinyin: "gǎi yí xià bào jià dān", meaning: "revise the quotation sheet" },
            { hanzi: "来晚了", pinyin: "lái wǎn le", meaning: "came late" },
            { hanzi: "不好意思", pinyin: "bù hǎo yì si", meaning: "sorry" },
            { hanzi: "我晚点到", pinyin: "wǒ wǎn diǎn dào", meaning: "I'll be late" },
            { hanzi: "我早点下班", pinyin: "wǒ zǎo diǎn xià bān", meaning: "I'll get off work early" },
            { hanzi: "早点来接我", pinyin: "zǎo diǎn lái jiē wǒ", meaning: "come pick me up early" },
            { hanzi: "长袖", pinyin: "cháng xiù", meaning: "long-sleeved" },
            { hanzi: "短袖", pinyin: "duǎn xiù", meaning: "short-sleeved" },
            { hanzi: "今晚", pinyin: "jīn wǎn", meaning: "tonight" },
            { hanzi: "今天", pinyin: "jīn tiān", meaning: "today" },
            { hanzi: "旧手机", pinyin: "jiù shǒu jī", meaning: "old phone" },
            { hanzi: "换手机", pinyin: "huàn shǒu jī", meaning: "change the phone" },
            { hanzi: "下单", pinyin: "xià dān", meaning: "place an order" },
            { hanzi: "订单号", pinyin: "dìng dān hào", meaning: "order number" },
            { hanzi: "饭店", pinyin: "fàn diàn", meaning: "restaurant" },
            { hanzi: "酒店", pinyin: "jiǔ diàn", meaning: "hotel" },
            { hanzi: "餐馆", pinyin: "cān guǎn", meaning: "restaurant" },
            { hanzi: "砍价", pinyin: "kǎn jià", meaning: "bargain" },
            { hanzi: "原价", pinyin: "yuán jià", meaning: "original price" },
            { hanzi: "折后价", pinyin: "zhé hòu jià", meaning: "discounted price" },
            { hanzi: "打折", pinyin: "dǎ zhé", meaning: "give a discount" },
            { hanzi: "打几折", pinyin: "dǎ jǐ zhé", meaning: "how much discount" },
            { hanzi: "有折扣吗", pinyin: "yǒu zhé kòu ma", meaning: "Is there a discount?" },
            { hanzi: "批量", pinyin: "pī liàng", meaning: "batch" },
            { hanzi: "数量", pinyin: "shù liàng", meaning: "quantity" },
            { hanzi: "女生", pinyin: "nǚ shēng", meaning: "female student" },
            { hanzi: "女孩子", pinyin: "nǚ hái zi", meaning: "girl" },
            { hanzi: "定金", pinyin: "dìng jīn", meaning: "deposit" },
            { hanzi: "美式", pinyin: "měi shì", meaning: "American style" },
            { hanzi: "中式", pinyin: "zhōng shì", meaning: "Chinese style" },
            { hanzi: "正式", pinyin: "zhèng shì", meaning: "formal" },
            { hanzi: "一份报价单", pinyin: "yí fèn bào jià dān", meaning: "a quotation sheet" },
            { hanzi: "飞机没有晚点", pinyin: "fēi jī méi yǒu wǎn diǎn", meaning: "the plane is not delayed" },
            { hanzi: "正点到达", pinyin: "zhèng diǎn dào dá", meaning: "arrive on time" },
            { hanzi: "条件", pinyin: "tiáo jiàn", meaning: "condition" },
            { hanzi: "付款条件", pinyin: "fù kuǎn tiáo jiàn", meaning: "payment terms" }
        ]
    },
    {
        id: 3,
        name: "New Words 3",
        words: [
            { hanzi: "女生", pinyin: "nǚ shēng", meaning: "girl" },
            { hanzi: "女孩子", pinyin: "nǚ hái zi", meaning: "girl" },
            { hanzi: "老头子", pinyin: "lǎo tóu zi", meaning: "old man" },
            { hanzi: "老太太", pinyin: "lǎo tài tai", meaning: "old lady" },
            { hanzi: "定金", pinyin: "dìng jīn", meaning: "earnest money / deposit" },
            { hanzi: "女士", pinyin: "nǚ shì", meaning: "lady" },
            { hanzi: "先生", pinyin: "xiān sheng", meaning: "gentleman / Mr." },
            { hanzi: "假期", pinyin: "jià qī", meaning: "vacation / holiday" },
            { hanzi: "运费", pinyin: "yùn fèi", meaning: "freight / shipping fee" },
            { hanzi: "出厂价", pinyin: "chū chǎng jià", meaning: "ex-factory price" },
            { hanzi: "本地人", pinyin: "běn dì rén", meaning: "local person" },
            { hanzi: "外地人", pinyin: "wài dì rén", meaning: "non-local person" },
            { hanzi: "近视手术", pinyin: "jìn shì shǒu shù", meaning: "myopia surgery" },
            { hanzi: "眼镜", pinyin: "yǎn jìng", meaning: "glasses" },
            { hanzi: "手表", pinyin: "shǒu biǎo", meaning: "watch" },
            { hanzi: "钟表", pinyin: "zhōng biǎo", meaning: "clocks and watches" },
            { hanzi: "表妹", pinyin: "biǎo mèi", meaning: "younger female cousin (mother’s side)" },
            { hanzi: "堂妹", pinyin: "táng mèi", meaning: "younger female cousin (father’s side)" },
            { hanzi: "皮带", pinyin: "pí dài", meaning: "belt" },
            { hanzi: "领带", pinyin: "lǐng dài", meaning: "tie" },
            { hanzi: "时刻表", pinyin: "shí kè biǎo", meaning: "timetable" },
            { hanzi: "刻字", pinyin: "kè zì", meaning: "engrave words" },
            { hanzi: "名人", pinyin: "míng rén", meaning: "celebrity" },
            { hanzi: "名声", pinyin: "míng shēng", meaning: "reputation" },
            { hanzi: "航班", pinyin: "háng bān", meaning: "flight" },
            { hanzi: "快递", pinyin: "kuài dì", meaning: "express delivery" },
            { hanzi: "外卖", pinyin: "wài mài", meaning: "takeout" },
            { hanzi: "课表", pinyin: "kè biǎo", meaning: "class schedule" },
            { hanzi: "大堂", pinyin: "dà táng", meaning: "lobby" },
            { hanzi: "大厅", pinyin: "dà tīng", meaning: "hall" },
            { hanzi: "感恩节", pinyin: "gǎn ēn jié", meaning: "Thanksgiving Day" },
            { hanzi: "恩人", pinyin: "ēn rén", meaning: "benefactor" },
            { hanzi: "晚点", pinyin: "wǎn diǎn", meaning: "delayed" },
            { hanzi: "正点", pinyin: "zhèng diǎn", meaning: "on time" },
            { hanzi: "谈工作", pinyin: "tán gōng zuò", meaning: "talk about work" },
            { hanzi: "谈价格", pinyin: "tán jià gé", meaning: "negotiate price" },
            { hanzi: "谈恋爱", pinyin: "tán liàn ài", meaning: "be in a relationship" },
            { hanzi: "恋人", pinyin: "liàn rén", meaning: "lover" },
            { hanzi: "爱人", pinyin: "ài rén", meaning: "spouse / lover" },
            { hanzi: "情人", pinyin: "qíng rén", meaning: "lover" },
            { hanzi: "通知", pinyin: "tōng zhī", meaning: "notify / notice" },
            { hanzi: "参加", pinyin: "cān jiā", meaning: "join / attend" },
            { hanzi: "报名", pinyin: "bào míng", meaning: "sign up" },
            { hanzi: "展销会", pinyin: "zhǎn xiāo huì", meaning: "trade fair" },
            { hanzi: "日历", pinyin: "rì lì", meaning: "calendar" },
            { hanzi: "农历", pinyin: "nóng lì", meaning: "lunar calendar" },
            { hanzi: "方案资料", pinyin: "fāng àn zī liào", meaning: "plan materials" },
            { hanzi: "有关资料", pinyin: "yǒu guān zī liào", meaning: "relevant materials" },
            { hanzi: "稍后", pinyin: "shāo hòu", meaning: "later" },
            { hanzi: "熟悉", pinyin: "shú xī", meaning: "be familiar with" },
            { hanzi: "年度计划方案", pinyin: "nián dù jì huà fāng àn", meaning: "annual plan" },
            { hanzi: "手头有点紧", pinyin: "shǒu tóu yǒu diǎn jǐn", meaning: "a bit short on money" },
            { hanzi: "西红柿炒鸡蛋", pinyin: "xī hóng shì chǎo jī dàn", meaning: "scrambled eggs with tomatoes" },
            { hanzi: "家常菜", pinyin: "jiā cháng cài", meaning: "home-cooked dishes" },
            { hanzi: "一顿饭", pinyin: "yī dùn fàn", meaning: "a meal" },
            { hanzi: "味道", pinyin: "wèi dào", meaning: "taste" },
            { hanzi: "合不合口味", pinyin: "hé bù hé kǒu wèi", meaning: "whether it suits the appetite" },
            { hanzi: "口味", pinyin: "kǒu wèi", meaning: "taste / flavor" },
            { hanzi: "工资", pinyin: "gōng zī", meaning: "salary" },
            { hanzi: "厨艺", pinyin: "chú yì", meaning: "cooking skills" },
            { hanzi: "厨师", pinyin: "chú shī", meaning: "chef" },
            { hanzi: "不合适", pinyin: "bù hé shì", meaning: "not suitable" },
            { hanzi: "开工", pinyin: "kāi gōng", meaning: "start work" },
            { hanzi: "在家办公", pinyin: "zài jiā bàn gōng", meaning: "work from home" },
            { hanzi: "线上办公", pinyin: "xiàn shàng bàn gōng", meaning: "work online" },
            { hanzi: "上网课", pinyin: "shàng wǎng kè", meaning: "take online courses" },
            { hanzi: "欧美", pinyin: "ōu měi", meaning: "Europe and America" },
            { hanzi: "我说了算", pinyin: "wǒ shuō le suàn", meaning: "I call the shots" },
            { hanzi: "零基础", pinyin: "líng jī chǔ", meaning: "zero foundation" },
            { hanzi: "享受生活", pinyin: "xiǎng shòu shēng huó", meaning: "enjoy life" },
            { hanzi: "不同", pinyin: "bù tóng", meaning: "different" },
            { hanzi: "闲聊", pinyin: "xián liáo", meaning: "chat casually" },
            { hanzi: "无聊", pinyin: "wú liáo", meaning: "boring" },
            { hanzi: "感受", pinyin: "gǎn shòu", meaning: "feel" },
            { hanzi: "感动", pinyin: "gǎn dòng", meaning: "be moved" },
            { hanzi: "分享", pinyin: "fēn xiǎng", meaning: "share" },
            { hanzi: "健身", pinyin: "jiàn shēn", meaning: "fitness" },
            { hanzi: "尝一尝", pinyin: "cháng yī cháng", meaning: "have a taste / try" },
            { hanzi: "试一试", pinyin: "shì yī shì", meaning: "have a try" },
            { hanzi: "夫人", pinyin: "fū rén", meaning: "madam / wife" },
            { hanzi: "先生", pinyin: "xiān sheng", meaning: "gentleman / husband" },
            { hanzi: "名不虚传", pinyin: "míng bù xū chuán", meaning: "deserves the reputation" },
            { hanzi: "虚心", pinyin: "xū xīn", meaning: "modestly" },
            { hanzi: "过奖了", pinyin: "guò jiǎng le", meaning: "you flatter me" },
            { hanzi: "好福气", pinyin: "hǎo fú qì", meaning: "good fortune" },
            { hanzi: "又漂亮又能干", pinyin: "yòu piào liang yòu néng gàn", meaning: "beautiful and capable" }
        ]
    }
];
