// words-data.js
// =====================
// 词库数据
// =====================


window.UNITS = [
    {
      id: 1,
      name: "New Words 1",
      words: [
            { hanzi: "未婚", pinyin: "wèi hūn", meaning: "not married; unmarried (formal)" },
            { hanzi: "未必", pinyin: "wèi bì", meaning: "not necessarily; used to soften certainty" },
            { hanzi: "未来", pinyin: "wèi lái", meaning: "the future; what’s to come" },
            { hanzi: "一壶茶", pinyin: "yì hú chá", meaning: "a pot of tea (壶 = measure word for a pot/kettle)" },
            { hanzi: "尽头", pinyin: "jìn tóu", meaning: "the end/endpoint (of a road, period, etc.)" },
            { hanzi: "年末", pinyin: "nián mò", meaning: "the end of the year (often for schedules/finance)" },
            { hanzi: "月末", pinyin: "yuè mò", meaning: "the end of the month" },
            { hanzi: "曾经", pinyin: "céng jīng", meaning: "once; formerly; at some time in the past" },
            { hanzi: "期末", pinyin: "qī mò", meaning: "end of term/semester; finals period" },
            { hanzi: "周末", pinyin: "zhōu mò", meaning: "weekend" },
            { hanzi: "火了", pinyin: "huǒ le", meaning: "(1) become popular/viral; (2) catch fire (context decides)" },
            { hanzi: "发火了", pinyin: "fā huǒ le", meaning: "got angry; lost one’s temper" },
            { hanzi: "脱单", pinyin: "tuō dān", meaning: "stop being single; get into a relationship" },
            { hanzi: "光棍儿", pinyin: "guāng gùn er", meaning: "bachelor/single person (colloquial; often teasing)" },
            { hanzi: "月光族", pinyin: "yuè guāng zú", meaning: "someone who spends all their salary each month (no savings)" },
            { hanzi: "光头佬", pinyin: "guāng tóu lǎo", meaning: "a bald guy (colloquial; can sound rude depending on tone)" },
            { hanzi: "促销价", pinyin: "cù xiāo jià", meaning: "promotional/sale price" },
            { hanzi: "成交价", pinyin: "chéng jiāo jià", meaning: "final transaction/deal price" },
            { hanzi: "团购价", pinyin: "tuán gòu jià", meaning: "group-buy price (discount for group purchase)" },
            { hanzi: "零售价", pinyin: "líng shòu jià", meaning: "retail price" },
            { hanzi: "利息", pinyin: "lì xī", meaning: "interest (money earned/paid on deposits/loans)" },
            { hanzi: "首付", pinyin: "shǒu fù", meaning: "down payment (first payment for house/car etc.)" },
            { hanzi: "免息", pinyin: "miǎn xī", meaning: "interest-free (e.g., 免息分期)" },
            { hanzi: "买卖", pinyin: "mǎi mài", meaning: "business; buying and selling (trade)" },
            { hanzi: "顾客", pinyin: "gù kè", meaning: "customer (store/service context)" },
            { hanzi: "找钱", pinyin: "zhǎo qián", meaning: "give change (return money after payment)" },
            { hanzi: "零钱", pinyin: "líng qián", meaning: "small change; coins/small bills" },
            { hanzi: "兑现", pinyin: "duì xiàn", meaning: "(1) cash in/exchange (voucher/check); (2) fulfill a promise (兑现承诺)" },
            { hanzi: "汇率", pinyin: "huì lǜ", meaning: "exchange rate" },
            { hanzi: "汇款", pinyin: "huì kuǎn", meaning: "remit money; make a transfer (often bank transfer)" },
            { hanzi: "山顶", pinyin: "shān dǐng", meaning: "mountaintop; top of a mountain" },
            { hanzi: "头顶", pinyin: "tóu dǐng", meaning: "top of the head; overhead" },
            { hanzi: "外汇", pinyin: "wài huì", meaning: "foreign exchange (forex; currency exchange market)" },
            { hanzi: "外币", pinyin: "wài bì", meaning: "foreign currency (cash/notes/coins)" },
            { hanzi: "师傅", pinyin: "shī fu", meaning: "a respectful way to address drivers/craftspeople; master" },
            { hanzi: "客人", pinyin: "kè rén", meaning: "guest; customer; visitor (context-dependent)" },
            { hanzi: "对面", pinyin: "duì miàn", meaning: "opposite; across from" },
            { hanzi: "一对儿", pinyin: "yí duìr", meaning: "a pair; a couple (colloquial, northern style)" },
            { hanzi: "现金", pinyin: "xiàn jīn", meaning: "cash" },
            { hanzi: "信用卡", pinyin: "xìn yòng kǎ", meaning: "credit card" },
            { hanzi: "房卡", pinyin: "fáng kǎ", meaning: "hotel room key card" },
            { hanzi: "差不多", pinyin: "chà bu duō", meaning: "almost; roughly; about the same" },
            { hanzi: "约会", pinyin: "yuē huì", meaning: "go on a date; appointment to meet (often romantic)" },
            { hanzi: "开会", pinyin: "kāi huì", meaning: "have/hold a meeting" },
            { hanzi: "硬币", pinyin: "yìng bì", meaning: "coin" },
            { hanzi: "纸币", pinyin: "zhǐ bì", meaning: "banknote; paper currency" },
            { hanzi: "货币", pinyin: "huò bì", meaning: "currency; money system (general term)" },
            { hanzi: "报价单", pinyin: "bào jià dān", meaning: "quotation sheet/document (price quote)" },
            { hanzi: "账单", pinyin: "zhàng dān", meaning: "bill; statement (what you need to pay)" },
            { hanzi: "菜单", pinyin: "cài dān", meaning: "menu" },
            { hanzi: "商品", pinyin: "shāng pǐn", meaning: "merchandise; goods for sale" },
            { hanzi: "物品", pinyin: "wù pǐn", meaning: "items; objects (general)" },
            { hanzi: "商店", pinyin: "shāng diàn", meaning: "shop; store" },
            { hanzi: "日用品", pinyin: "rì yòng pǐn", meaning: "daily necessities; everyday items" },
            { hanzi: "产品", pinyin: "chǎn pǐn", meaning: "product (often business/manufacturing context)" },
            { hanzi: "自我介绍", pinyin: "zì wǒ jiè shào", meaning: "self-introduction (formal/common)" },
            { hanzi: "个人信息", pinyin: "gè rén xìn xī", meaning: "personal information (name, phone, etc.)" },
            { hanzi: "表格", pinyin: "biǎo gé", meaning: "form/table to fill in" },
            { hanzi: "固话", pinyin: "gù huà", meaning: "landline phone (fixed-line)" },
            { hanzi: "网址", pinyin: "wǎng zhǐ", meaning: "website address; URL" },
            { hanzi: "双床房", pinyin: "shuāng chuáng fáng", meaning: "twin room (two beds)" },
            { hanzi: "大床房", pinyin: "dà chuáng fáng", meaning: "one large bed room (king/queen room)" },
            { hanzi: "订机票", pinyin: "dìng jī piào", meaning: "book flight tickets" },
            { hanzi: "微信", pinyin: "Wēi xìn", meaning: "WeChat (app; messaging/payments)" },
            { hanzi: "模板", pinyin: "mó bǎn", meaning: "template; reusable format/model" },
            { hanzi: "职责", pinyin: "zhí zé", meaning: "duties; responsibilities (job role)" },
            { hanzi: "项目", pinyin: "xiàng mù", meaning: "project; program/item (business context)" },
            { hanzi: "近期", pinyin: "jìn qī", meaning: "recently; in the near term" },
            { hanzi: "成就", pinyin: "chéng jiù", meaning: "achievement; accomplishment" },
            { hanzi: "岗位", pinyin: "gǎng wèi", meaning: "job post/position (HR/business term)" },
            { hanzi: "手头紧", pinyin: "shǒu tóu jǐn", meaning: "short of money; cash-strapped (colloquial)" },
            { hanzi: "商务汉语", pinyin: "shāng wù hàn yǔ", meaning: "Business Chinese" },
            { hanzi: "发展空间", pinyin: "fā zhǎn kōng jiān", meaning: "room for growth; development potential" },
            { hanzi: "书面", pinyin: "shū miàn", meaning: "written (style); formal writing" },
            { hanzi: "口头", pinyin: "kǒu tóu", meaning: "spoken/oral (style)" },
            { hanzi: "资料", pinyin: "zī liào", meaning: "materials; documents; data/information" },
            { hanzi: "品牌", pinyin: "pǐn pái", meaning: "brand" },
            { hanzi: "化学", pinyin: "huà xué", meaning: "chemistry" },
            { hanzi: "点菜", pinyin: "diǎn cài", meaning: "order dishes (at a restaurant)" },
            { hanzi: "该你了", pinyin: "gāi nǐ le", meaning: "your turn (to do/say/pay etc.)" },
            { hanzi: "活动", pinyin: "huó dòng", meaning: "activity; event (organized)" },
            { hanzi: "靓女", pinyin: "liàng nǚ", meaning: "pretty girl (colloquial; Cantonese-influenced)" },
            { hanzi: "小妹", pinyin: "xiǎo mèi", meaning: "little sister; casual address for a young woman (context-sensitive)" },
            { hanzi: "称呼", pinyin: "chēng hu", meaning: "how you address/call someone; title" },
            { hanzi: "怎么称呼您呢", pinyin: "zěn me chēng hu nín ne", meaning: "How should I address you? (very polite)" },
            { hanzi: "靓仔", pinyin: "liàng zǎi", meaning: "handsome guy (colloquial; Cantonese-influenced)" },
            { hanzi: "见面", pinyin: "jiàn miàn", meaning: "meet (in person)" },
            { hanzi: "看见", pinyin: "kàn jiàn", meaning: "see; catch sight of" },
            { hanzi: "接客人", pinyin: "jiē kè rén", meaning: "pick up/receive guests (e.g., at airport/hotel)" },
            { hanzi: "见客人", pinyin: "jiàn kè rén", meaning: "meet with guests/clients" },
            { hanzi: "什么时候", pinyin: "shén me shí hou", meaning: "when (at what time)" },
            { hanzi: "啥时候", pinyin: "shá shí hou", meaning: "when (colloquial version of 什么时候)" },
            { hanzi: "来得及", pinyin: "lái de jí", meaning: "have enough time; make it in time" },
            { hanzi: "来不及", pinyin: "lái bu jí", meaning: "not enough time; too late; can’t make it" },
            { hanzi: "活期", pinyin: "huó qī", meaning: "demand deposit; current account (banking)" },
            { hanzi: "定期", pinyin: "dìng qī", meaning: "fixed-term deposit (banking)" },
            { hanzi: "利率", pinyin: "lì lǜ", meaning: "interest rate (percentage)" },
            { hanzi: "一个点", pinyin: "yí ge diǎn", meaning: "one percentage point (business way to say 1%)" },
            { hanzi: "卖家", pinyin: "mài jiā", meaning: "seller" },
            { hanzi: "买家", pinyin: "mǎi jiā", meaning: "buyer" },
            { hanzi: "商家", pinyin: "shāng jiā", meaning: "merchant/vendor; business owner" },
            { hanzi: "讨厌", pinyin: "tǎo yàn", meaning: "dislike; find annoying (stronger than 不喜欢)" },
            { hanzi: "展销会", pinyin: "zhǎn xiāo huì", meaning: "exhibition and sales fair; trade fair with selling" },
            { hanzi: "展馆", pinyin: "zhǎn guǎn", meaning: "exhibition hall/pavilion (venue)" },
            { hanzi: "参展", pinyin: "cān zhǎn", meaning: "take part in an exhibition (as exhibitor)" },
            { hanzi: "看展", pinyin: "kàn zhǎn", meaning: "visit an exhibition (as visitor)" },
            { hanzi: "我该走了", pinyin: "wǒ gāi zǒu le", meaning: "I should get going now (polite way to leave)" },
            { hanzi: "开头", pinyin: "kāi tóu", meaning: "beginning; start (of story/event)" },
            { hanzi: "老家", pinyin: "lǎo jiā", meaning: "hometown; native place (where family is from)" },
            { hanzi: "老板", pinyin: "lǎo bǎn", meaning: "boss; shop owner" },
            { hanzi: "快点儿", pinyin: "kuài diǎn er", meaning: "hurry up; a bit faster (colloquial)" },
            { hanzi: "餐馆", pinyin: "cān guǎn", meaning: "restaurant (general)" },
            { hanzi: "饭馆", pinyin: "fàn guǎn", meaning: "eatery/restaurant (more colloquial)" },
            { hanzi: "打招呼", pinyin: "dǎ zhāo hu", meaning: "greet; say hello; acknowledge" },
            { hanzi: "这事儿就这么定了", pinyin: "zhè shìr jiù zhè me dìng le", meaning: "It’s settled; that’s decided (final decision)" },
            { hanzi: "就这么定吧", pinyin: "jiù zhè me dìng ba", meaning: "Let’s settle it like this; let’s decide this way" },
            { hanzi: "地道", pinyin: "dì dào", meaning: "authentic; genuine; idiomatic (language/food)" },
            { hanzi: "匆忙", pinyin: "cōng máng", meaning: "in a hurry; rushed" },
            { hanzi: "匆匆忙忙", pinyin: "cōng cōng máng máng", meaning: "hurriedly; in a great rush" },
            { hanzi: "忙忙碌碌", pinyin: "máng máng lù lù", meaning: "busy and occupied (describes a busy life/day)" },
            { hanzi: "马马虎虎", pinyin: "mǎ mǎ hū hū", meaning: "so-so; careless; not very good but acceptable" },
            { hanzi: "花多少钱", pinyin: "huā duō shao qián", meaning: "how much money does it cost/spend?" },
            { hanzi: "花多少时间", pinyin: "huā duō shao shí jiān", meaning: "how much time does it take/spend?" },
            { hanzi: "花钱", pinyin: "huā qián", meaning: "spend money" },
            { hanzi: "花时间", pinyin: "huā shí jiān", meaning: "spend time" },
            { hanzi: "定金", pinyin: "dìng jīn", meaning: "deposit (money paid to secure a deal/order)" },
            { hanzi: "熟悉", pinyin: "shú xī", meaning: "be familiar with (people/places/topics)" },
            { hanzi: "饭熟了", pinyin: "fàn shú le", meaning: "the rice is cooked (熟 = cooked/ready)" },
            { hanzi: "芒果熟了", pinyin: "máng guǒ shú le", meaning: "the mango is ripe (熟 = ripe)" },
            { hanzi: "你和他熟悉吗", pinyin: "nǐ hé tā shú xī ma", meaning: "Are you familiar with him? (know him well?)" },
            { hanzi: "结账", pinyin: "jié zhàng", meaning: "pay the bill; check out" },
            { hanzi: "端过来", pinyin: "duān guò lái", meaning: "bring it over (carrying in hands; dishes/drinks)" },
            { hanzi: "谢谢您的支持", pinyin: "xiè xie nín de zhī chí", meaning: "thank you for your support (polite service phrase)" },
            { hanzi: "买单", pinyin: "mǎi dān", meaning: "pay the bill (colloquial; often at restaurants)" },
            { hanzi: "中餐", pinyin: "zhōng cān", meaning: "Chinese food/meal" },
            { hanzi: "午餐", pinyin: "wǔ cān", meaning: "lunch" },
            { hanzi: "西餐", pinyin: "xī cān", meaning: "Western food/meal" },
            { hanzi: "请慢用", pinyin: "qǐng màn yòng", meaning: "please enjoy your meal (restaurant phrase)" },
            { hanzi: "用餐愉快", pinyin: "yòng cān yú kuài", meaning: "enjoy your meal (polite phrase)" },
            { hanzi: "我来", pinyin: "wǒ lái", meaning: "Let me do it / I’ll take it (often said when offering to pay/do)" },
            { hanzi: "我来买单", pinyin: "wǒ lái mǎi dān", meaning: "I’ll pay the bill (offering to treat)" },
            { hanzi: "请客", pinyin: "qǐng kè", meaning: "treat someone (pay for their meal/drinks)" },
            { hanzi: "主食", pinyin: "zhǔ shí", meaning: "staple food (rice/noodles/bread)" },
            { hanzi: "水果", pinyin: "shuǐ guǒ", meaning: "fruit" },
            { hanzi: "面条", pinyin: "miàn tiáo", meaning: "noodles" },
            { hanzi: "米饭", pinyin: "mǐ fàn", meaning: "cooked rice" },
            { hanzi: "零食", pinyin: "líng shí", meaning: "snacks (between meals)" },
            { hanzi: "甜点", pinyin: "tián diǎn", meaning: "dessert" },
            { hanzi: "点心", pinyin: "diǎn xin", meaning: "snacks/pastries; also dim sum (context/region dependent)" },
            { hanzi: "很高兴认识二位", pinyin: "hěn gāo xìng rèn shi èr wèi", meaning: "Nice to meet you two (二位 = two people, polite)" },
            { hanzi: "请问几位", pinyin: "qǐng wèn jǐ wèi", meaning: "How many people? (restaurant politeness)" },
            { hanzi: "举杯", pinyin: "jǔ bēi", meaning: "raise a glass (to toast)" },
            { hanzi: "举手", pinyin: "jǔ shǒu", meaning: "raise one’s hand" },
            { hanzi: "举手之劳", pinyin: "jǔ shǒu zhī láo", meaning: "a small effort; “just a little favor” (idiom)" },
            { hanzi: "招待", pinyin: "zhāo dài", meaning: "receive/entertain (guests); treat hospitably" },
            { hanzi: "喝点什么", pinyin: "hē diǎn shén me", meaning: "what would you like to drink? (casual)" },
            { hanzi: "这回我请", pinyin: "zhè huí wǒ qǐng", meaning: "This time it’s on me (I’ll treat)" },
            { hanzi: "下回你请", pinyin: "xià huí nǐ qǐng", meaning: "Next time you treat (friendly arrangement/joking)" },
            { hanzi: "成交", pinyin: "chéng jiāo", meaning: "close a deal; make a transaction" },
            { hanzi: "准时", pinyin: "zhǔn shí", meaning: "on time; punctual" },
            { hanzi: "当时", pinyin: "dāng shí", meaning: "at that time; then" },
            { hanzi: "当天", pinyin: "dāng tiān", meaning: "that same day" },
            { hanzi: "再来一份儿", pinyin: "zài lái yí fènr", meaning: "one more portion, please (restaurant)" },
            { hanzi: "看不起", pinyin: "kàn bu qǐ", meaning: "look down on; despise" },
            { hanzi: "瞧不起", pinyin: "qiáo bu qǐ", meaning: "look down on (similar to 看不起; more colloquial)" },
            { hanzi: "看得起", pinyin: "kàn de qǐ", meaning: "think highly of; respect; value" },
            { hanzi: "看上", pinyin: "kàn shàng", meaning: "take a liking to; fancy; choose (person/item)" },
            { hanzi: "餐桌礼仪", pinyin: "cān zhuō lǐ yí", meaning: "table manners; dining etiquette" },
            { hanzi: "鱼头", pinyin: "yú tóu", meaning: "fish head (often mentioned in dining etiquette)" },
            { hanzi: "座位", pinyin: "zuò wèi", meaning: "seat; seating position" },
            { hanzi: "干杯", pinyin: "gān bēi", meaning: "cheers (toast; literally “dry the cup”)" },
            { hanzi: "友谊", pinyin: "yǒu yì", meaning: "friendship" },
            { hanzi: "为我们的友谊干杯", pinyin: "wèi wǒ men de yǒu yì gān bēi", meaning: "Cheers to our friendship (toast phrase)" },
            { hanzi: "公筷", pinyin: "gōng kuài", meaning: "serving/public chopsticks (hygiene at meals)" },
            { hanzi: "长寿", pinyin: "cháng shòu", meaning: "longevity; long life (wishes/toasts)" },
            { hanzi: "长寿面", pinyin: "cháng shòu miàn", meaning: "longevity noodles (birthday tradition)" },
            { hanzi: "您高寿", pinyin: "nín gāo shòu", meaning: "your age (very polite/old-fashioned way to ask an elder’s age)" },
            { hanzi: "请假条", pinyin: "qǐng jià tiáo", meaning: "leave note/form (written request for leave)" },
            { hanzi: "写作", pinyin: "xiě zuò", meaning: "writing; composition (skill/course)" },
            { hanzi: "出差", pinyin: "chū chāi", meaning: "go on a business trip" },
            { hanzi: "病假", pinyin: "bìng jià", meaning: "sick leave" },
            { hanzi: "事假", pinyin: "shì jià", meaning: "personal leave (for private matters)" },
            { hanzi: "感恩节", pinyin: "gǎn ēn jié", meaning: "Thanksgiving" },
            { hanzi: "工资条", pinyin: "gōng zī tiáo", meaning: "pay slip; salary statement" },
            { hanzi: "批准", pinyin: "pī zhǔn", meaning: "approve; give official permission" },
            { hanzi: "感冒", pinyin: "gǎn mào", meaning: "catch a cold; common cold" },
            { hanzi: "拉肚子", pinyin: "lā dù zi", meaning: "have diarrhea (colloquial)" },
            { hanzi: "流鼻涕", pinyin: "liú bí tì", meaning: "have a runny nose" },
            { hanzi: "头疼", pinyin: "tóu téng", meaning: "have a headache" },
            { hanzi: "嗓子疼", pinyin: "sǎng zi téng", meaning: "have a sore throat" },
            { hanzi: "发烧", pinyin: "fā shāo", meaning: "have a fever" },
            { hanzi: "东西", pinyin: "dōng xi", meaning: "(1) thing/stuff; (2) in insults: “what kind of person/thing” (very rude)" },
            { hanzi: "他是个什么东西", pinyin: "tā shì ge shén me dōng xi", meaning: "an insulting way to say “what kind of person is he?” (very rude)" },
            { hanzi: "他不是个好东西", pinyin: "tā bú shì ge hǎo dōng xi", meaning: "an insulting way to say “he’s no good” (very rude)" },
            { hanzi: "直说", pinyin: "zhí shuō", meaning: "say it directly; be straightforward" },
            { hanzi: "直走", pinyin: "zhí zǒu", meaning: "go straight" },
            { hanzi: "直接", pinyin: "zhí jiē", meaning: "direct; directly; without detours" },
            { hanzi: "一直", pinyin: "yì zhí", meaning: "all the time; continuously" },
            { hanzi: "董事长", pinyin: "dǒng shì zhǎng", meaning: "chairman of the board" },
            { hanzi: "总经理", pinyin: "zǒng jīng lǐ", meaning: "general manager (often GM/CEO depending on company)" },
            { hanzi: "销售经理", pinyin: "xiāo shòu jīng lǐ", meaning: "sales manager" },
            { hanzi: "人事助理", pinyin: "rén shì zhù lǐ", meaning: "HR assistant" },
            { hanzi: "部门", pinyin: "bù mén", meaning: "department" },
            { hanzi: "景观设计师", pinyin: "jǐng guān shè jì shī", meaning: "landscape designer/architect" },
            { hanzi: "提醒", pinyin: "tí xǐng", meaning: "remind; give a reminder" },
            { hanzi: "提前", pinyin: "tí qián", meaning: "in advance; ahead of schedule" },
            { hanzi: "关系", pinyin: "guān xi", meaning: "relationship/connection; also: relevance (有关系/没关系)" },
            { hanzi: "情人", pinyin: "qíng rén", meaning: "lover; romantic partner (context-sensitive)" },
            { hanzi: "仇人", pinyin: "chóu rén", meaning: "enemy (personal)" },
            { hanzi: "恩人", pinyin: "ēn rén", meaning: "benefactor; someone who helped you a lot" },
            { hanzi: "师生", pinyin: "shī shēng", meaning: "teachers and students (as a group/relationship)" },
            { hanzi: "亲人", pinyin: "qīn rén", meaning: "family; loved ones; close relatives" },
            { hanzi: "爱人", pinyin: "ài ren", meaning: "spouse/partner (often used as ‘my husband/wife’)" },
            { hanzi: "大人不和小人计", pinyin: "dà rén bù hé xiǎo rén jì", meaning: "a gentleman doesn’t stoop to petty people (idiomatic saying)" },
            { hanzi: "做事先做人", pinyin: "zuò shì xiān zuò rén", meaning: "before doing things, be a good person (emphasizes character)" },
            { hanzi: "小事儿", pinyin: "xiǎo shìr", meaning: "a small matter; trivial thing" },
            { hanzi: "关心", pinyin: "guān xīn", meaning: "care about; show concern" },
            { hanzi: "开心", pinyin: "kāi xīn", meaning: "happy; cheerful" },
            { hanzi: "担心", pinyin: "dān xīn", meaning: "worry; be concerned" },
            { hanzi: "一块儿", pinyin: "yí kuàir", meaning: "together; at the same time/place (colloquial)" },
            { hanzi: "几块钱", pinyin: "jǐ kuài qián", meaning: "a few yuan (kuài = colloquial for 元)" },
            { hanzi: "航站楼", pinyin: "háng zhàn lóu", meaning: "airport terminal building" },
            { hanzi: "辛苦", pinyin: "xīn kǔ", meaning: "hard/tiring; also used as “Thanks for your hard work”" },
            { hanzi: "顺利", pinyin: "shùn lì", meaning: "smoothly; without problems (e.g., 一路顺利)" },
            { hanzi: "生意", pinyin: "shēng yì", meaning: "business; trade (often about making money)" },
            { hanzi: "直飞", pinyin: "zhí fēi", meaning: "direct flight" },
            { hanzi: "转机", pinyin: "zhuǎn jī", meaning: "transfer; connecting flight" },
            { hanzi: "迟到", pinyin: "chí dào", meaning: "be late" },
            { hanzi: "晚点", pinyin: "wǎn diǎn", meaning: "delayed (for flights/trains); also: a bit later" },
            { hanzi: "正点", pinyin: "zhèng diǎn", meaning: "on time; punctual (transportation)" },
            { hanzi: "马上要起飞了", pinyin: "mǎ shàng yào qǐ fēi le", meaning: "it’s about to take off" },
            { hanzi: "不过试试", pinyin: "bú guò shì shi", meaning: "just give it a try anyway (not too hopeful)" },
            { hanzi: "不错", pinyin: "bú cuò", meaning: "not bad; pretty good" },
            { hanzi: "很不错", pinyin: "hěn bú cuò", meaning: "really good; quite nice" },
            { hanzi: "人齐了", pinyin: "rén qí le", meaning: "everyone is here (all people have arrived)" },
            { hanzi: "行李齐了", pinyin: "xíng li qí le", meaning: "all the luggage is here/complete" },
            { hanzi: "停车场", pinyin: "tíng chē chǎng", meaning: "parking lot" },
            { hanzi: "倒车", pinyin: "dǎo chē", meaning: "reverse a car; back up" },
            { hanzi: "差别", pinyin: "chā bié", meaning: "difference (between things)" },
            { hanzi: "时差", pinyin: "shí chā", meaning: "time difference; jet lag context" },
            { hanzi: "接风", pinyin: "jiē fēng", meaning: "welcome banquet/meal for someone arriving (host them)" },
            { hanzi: "期待", pinyin: "qī dài", meaning: "look forward to; expectation" },
            { hanzi: "困不困", pinyin: "kùn bú kùn", meaning: "are you sleepy?" },
            { hanzi: "累不累", pinyin: "lèi bú lèi", meaning: "are you tired?" },
            { hanzi: "一路辛苦了", pinyin: "yí lù xīn kǔ le", meaning: "thanks for the hard journey (polite to someone who traveled)" },
            { hanzi: "厚脸皮", pinyin: "hòu liǎn pí", meaning: "thick-skinned; shameless (colloquial)" },
            { hanzi: "脸皮薄", pinyin: "liǎn pí báo", meaning: "thin-skinned; easily embarrassed" },
            { hanzi: "空调", pinyin: "kōng tiáo", meaning: "air conditioner" },
            { hanzi: "改变", pinyin: "gǎi biàn", meaning: "change (make something different)" },
            { hanzi: "变化", pinyin: "biàn huà", meaning: "change (the change itself; development)" },
            { hanzi: "核心句", pinyin: "hé xīn jù", meaning: "core sentence/pattern (key sentence for practice)" },
            { hanzi: "亲切", pinyin: "qīn qiè", meaning: "kind; friendly; warm (manner/attitude)" },
            { hanzi: "今后", pinyin: "jīn hòu", meaning: "from now on; in the future" },
            { hanzi: "正门", pinyin: "zhèng mén", meaning: "main entrance" },
            { hanzi: "正面", pinyin: "zhèng miàn", meaning: "front side; positive aspect" },
            { hanzi: "反面", pinyin: "fǎn miàn", meaning: "back side; negative aspect" },
            { hanzi: "想不想", pinyin: "xiǎng bú xiǎng", meaning: "want to or not? / miss or not? (depends on verb 想)" },
            { hanzi: "算不算", pinyin: "suàn bú suàn", meaning: "does it count or not?" },
            { hanzi: "有钱人", pinyin: "yǒu qián rén", meaning: "a rich person" },
            { hanzi: "贵公司", pinyin: "guì gōng sī", meaning: "your esteemed company (polite business term)" },
            { hanzi: "熬夜", pinyin: "áo yè", meaning: "stay up late (often unwillingly)" },
            { hanzi: "夜猫子", pinyin: "yè māo zi", meaning: "night owl (someone who sleeps late)" },
            { hanzi: "到底", pinyin: "dào dǐ", meaning: "after all; to the end; used for emphasis (“what on earth”)"},
            { hanzi: "上飞机", pinyin: "shàng fēi jī", meaning: "board the plane" },
            { hanzi: "下飞机", pinyin: "xià fēi jī", meaning: "get off the plane" },
            { hanzi: "不必了", pinyin: "bú bì le", meaning: "no need (polite refusal)" },
            { hanzi: "不用送", pinyin: "bú yòng sòng", meaning: "no need to see me off / no need to escort" },
            { hanzi: "慢慢来", pinyin: "màn man lái", meaning: "take your time; don’t rush" },
            { hanzi: "欢迎光临", pinyin: "huān yíng guāng lín", meaning: "welcome (store/service phrase)" },
            { hanzi: "出入口", pinyin: "chū rù kǒu", meaning: "entrance/exit (combined)" },
            { hanzi: "出口", pinyin: "chū kǒu", meaning: "exit; also: export (context)" },
            { hanzi: "荣幸", pinyin: "róng xìng", meaning: "honor/privilege (e.g., 很荣幸认识您)" },
            { hanzi: "邀请", pinyin: "yāo qǐng", meaning: "invite (formally)" },
            { hanzi: "国际电话", pinyin: "guó jì diàn huà", meaning: "international call" },
            { hanzi: "导游", pinyin: "dǎo yóu", meaning: "tour guide" },
            { hanzi: "保姆", pinyin: "bǎo mǔ", meaning: "nanny; domestic helper" },
            { hanzi: "助理", pinyin: "zhù lǐ", meaning: "assistant" },
            { hanzi: "建议", pinyin: "jiàn yì", meaning: "suggest; recommendation" },
            { hanzi: "参观", pinyin: "cān guān", meaning: "visit (a place) (e.g., factory/museum)" },
            { hanzi: "考察", pinyin: "kǎo chá", meaning: "inspect/investigate (often business/official visit)" },
            { hanzi: "阿姨", pinyin: "ā yí", meaning: "auntie; also polite address for middle-aged woman/housekeeper" },
            { hanzi: "提问", pinyin: "tí wèn", meaning: "ask a question (formal)" },
            { hanzi: "粗心", pinyin: "cū xīn", meaning: "careless; not attentive" },
            { hanzi: "细心", pinyin: "xì xīn", meaning: "careful; attentive to details" },
            { hanzi: "占小便宜吃大亏", pinyin: "zhàn xiǎo pián yi chī dà kuī", meaning: "taking small advantages may lead to big losses (saying)" },
            { hanzi: "小心", pinyin: "xiǎo xīn", meaning: "be careful; watch out" },
            { hanzi: "不小心", pinyin: "bù xiǎo xīn", meaning: "accidentally; not careful" },
            { hanzi: "照顾", pinyin: "zhào gù", meaning: "take care of; look after; also: patronize (shop)" },
            { hanzi: "合适", pinyin: "hé shì", meaning: "suitable; appropriate" },
            { hanzi: "确认", pinyin: "què rèn", meaning: "confirm (check and verify)" },
            { hanzi: "确定", pinyin: "què dìng", meaning: "be sure/decide; certain (more about certainty/decision)" },
            { hanzi: "你真牛", pinyin: "nǐ zhēn niú", meaning: "you’re awesome (slang compliment)" },
            { hanzi: "行李", pinyin: "xíng li", meaning: "luggage" },
            { hanzi: "碰头", pinyin: "pèng tóu", meaning: "bump one’s head" },
            { hanzi: "下雨", pinyin: "xià yǔ", meaning: "rain; it’s raining" },
            { hanzi: "地滑", pinyin: "dì huá", meaning: "the ground is slippery" },
            { hanzi: "有电", pinyin: "yǒu diàn", meaning: "has power/battery; has electricity" },
            { hanzi: "现实", pinyin: "xiàn shí", meaning: "reality; realistic" },
            { hanzi: "面对现实", pinyin: "miàn duì xiàn shí", meaning: "face reality" },
            { hanzi: "到头来", pinyin: "dào tóu lái", meaning: "in the end; eventually (often after twists)" },
            { hanzi: "国际", pinyin: "guó jì", meaning: "international" },
            { hanzi: "人际", pinyin: "rén jì", meaning: "interpersonal (e.g., 人际关系)" },
            { hanzi: "交际", pinyin: "jiāo jì", meaning: "socialize; social interaction" },
            { hanzi: "天际", pinyin: "tiān jì", meaning: "horizon; edge of the sky (literary)" },
            { hanzi: "结局", pinyin: "jié jú", meaning: "ending (of a story); final outcome" },
            { hanzi: "结束", pinyin: "jié shù", meaning: "end; finish (verb)" },
            { hanzi: "结果", pinyin: "jié guǒ", meaning: "result; outcome (what comes out at the end)" },
            { hanzi: "故事的结局", pinyin: "gù shì de jié jú", meaning: "the ending of the story" },
            { hanzi: "事情的结果", pinyin: "shì qíng de jié guǒ", meaning: "the result of the matter" },
            { hanzi: "告别", pinyin: "gào bié", meaning: "say goodbye; farewell" },
            { hanzi: "一举两得", pinyin: "yì jǔ liǎng dé", meaning: "kill two birds with one stone (idiom)" },
            { hanzi: "后会无期", pinyin: "hòu huì wú qī", meaning: "no promise we’ll meet again (farewell phrase; dramatic)" },
            { hanzi: "后会有期", pinyin: "hòu huì yǒu qī", meaning: "we’ll meet again someday (farewell phrase)" },
            { hanzi: "忙碌", pinyin: "máng lù", meaning: "busy (formal-ish)" },
            { hanzi: "鞠躬", pinyin: "jū gōng", meaning: "bow (as greeting/apology/respect)" },
            { hanzi: "会客", pinyin: "huì kè", meaning: "receive guests/clients (formal/business)" },
            { hanzi: "会面", pinyin: "huì miàn", meaning: "meet formally; have a meeting (more formal than 见面)" },
            { hanzi: "日程安排", pinyin: "rì chéng ān pái", meaning: "schedule/itinerary arrangement" },
            { hanzi: "叙述", pinyin: "xù shù", meaning: "narrate; recount" },
            { hanzi: "情节", pinyin: "qíng jié", meaning: "plot (story/movie)" },
            { hanzi: "无聊", pinyin: "wú liáo", meaning: "boring; bored (no interesting things)" },
            { hanzi: "聊天框", pinyin: "liáo tiān kuàng", meaning: "chat box/window (UI)" },
            { hanzi: "寂寞", pinyin: "jì mò", meaning: "lonely (more emotional/solitary than 无聊)" },
            { hanzi: "无趣", pinyin: "wú qù", meaning: "not interesting; lacking fun" },
            { hanzi: "没意思", pinyin: "méi yì si", meaning: "not interesting; pointless; not fun" },
            { hanzi: "点赞", pinyin: "diǎn zàn", meaning: "give a like (online)" },
            { hanzi: "听了个寂寞", pinyin: "tīng le ge jì mò", meaning: "a meme: ‘listened for nothing / got nothing out of it’" },
            { hanzi: "感兴趣", pinyin: "gǎn xìng qù", meaning: "be interested in" },
            { hanzi: "兴趣", pinyin: "xìng qù", meaning: "interest (hobby/curiosity)" },
            { hanzi: "有趣", pinyin: "yǒu qù", meaning: "interesting; fun" },
            { hanzi: "睡懒觉", pinyin: "shuì lǎn jiào", meaning: "sleep in; stay in bed late" },
            { hanzi: "送礼", pinyin: "sòng lǐ", meaning: "give a gift (often in social etiquette)" },
            { hanzi: "够意思", pinyin: "gòu yì si", meaning: "loyal/generous; ‘you’re a real friend’ (colloquial)" },
            { hanzi: "犯错", pinyin: "fàn cuò", meaning: "make a mistake" },
            { hanzi: "人不犯我，我不犯人", pinyin: "rén bú fàn wǒ, wǒ bú fàn rén", meaning: "if others don’t mess with me, I won’t mess with them (saying)" },
            { hanzi: "发型", pinyin: "fà xíng", meaning: "hairstyle" },
            { hanzi: "做头发", pinyin: "zuò tóu fa", meaning: "do one’s hair (salon: styling/treatment)" },
            { hanzi: "理发", pinyin: "lǐ fà", meaning: "get a haircut" },
            { hanzi: "造型", pinyin: "zào xíng", meaning: "style; styling (hair/look)" },
            { hanzi: "快剪", pinyin: "kuài jiǎn", meaning: "quick haircut service (fast cut)" },
            { hanzi: "很自然", pinyin: "hěn zì rán", meaning: "looks natural (e.g., hair/makeup/result)" },
            { hanzi: "很适合你", pinyin: "hěn shì hé nǐ", meaning: "it suits you well" },
            { hanzi: "吓我", pinyin: "xià wǒ", meaning: "scare me" },
            { hanzi: "真的吗", pinyin: "zhēn de ma", meaning: "really?; is that true?" },
            { hanzi: "短视频", pinyin: "duǎn shì pín", meaning: "short video (platform content format)" },
            { hanzi: "打车", pinyin: "dǎ chē", meaning: "take a taxi/ride-hailing" },
            { hanzi: "打的", pinyin: "dǎ dī", meaning: "take a taxi (older/colloquial)" },
            { hanzi: "开车", pinyin: "kāi chē", meaning: "drive a car" },
            { hanzi: "坐车", pinyin: "zuò chē", meaning: "ride in a vehicle; take transport" },
            { hanzi: "不好意思", pinyin: "bù hǎo yì si", meaning: "(1) sorry/excuse me; (2) embarrassed (context)" },
            { hanzi: "借过", pinyin: "jiè guò", meaning: "excuse me, let me pass (squeezing through crowd)" },
            { hanzi: "别在湖里游泳", pinyin: "bié zài hú lǐ yóu yǒng", meaning: "don’t swim in the lake (warning)" },
            { hanzi: "太高了", pinyin: "tài gāo le", meaning: "too high" },
            { hanzi: "够不着", pinyin: "gòu bu zháo", meaning: "can’t reach (too far/high)" },
            { hanzi: "有借有还，再借不难", pinyin: "yǒu jiè yǒu huán, zài jiè bù nán", meaning: "if you borrow and return, borrowing again is easy (saying)" },
            { hanzi: "成年人", pinyin: "chéng nián rén", meaning: "adult" },
            { hanzi: "男人", pinyin: "nán rén", meaning: "man" },
            { hanzi: "女人", pinyin: "nǚ rén", meaning: "woman" },
            { hanzi: "过一生", pinyin: "guò yì shēng", meaning: "live one’s whole life" },
            { hanzi: "公共汽车", pinyin: "gōng gòng qì chē", meaning: "public bus" },
            { hanzi: "公交车", pinyin: "gōng jiāo chē", meaning: "bus (short for 公共汽车)" },
            { hanzi: "预约", pinyin: "yù yuē", meaning: "make an appointment/reservation" },
            { hanzi: "公事", pinyin: "gōng shì", meaning: "public/official business (work matters)" },
            { hanzi: "私事", pinyin: "sī shì", meaning: "private matters" },
            { hanzi: "自私", pinyin: "zì sī", meaning: "selfish" },
            { hanzi: "公私分明", pinyin: "gōng sī fēn míng", meaning: "draw a clear line between public and private (principled)" },
            { hanzi: "倒霉", pinyin: "dǎo méi", meaning: "have bad luck; unlucky" },
            { hanzi: "锻炼", pinyin: "duàn liàn", meaning: "exercise; work out; train" },
            { hanzi: "堵车", pinyin: "dǔ chē", meaning: "traffic jam; heavy traffic" },
            { hanzi: "土生土长", pinyin: "tǔ shēng tǔ zhǎng", meaning: "born and raised locally; native" },
            { hanzi: "长生不老", pinyin: "cháng shēng bù lǎo", meaning: "live forever; be immortal (mythic/idiom)" },
            { hanzi: "生命", pinyin: "shēng mìng", meaning: "life (as existence)" },
            { hanzi: "生活", pinyin: "shēng huó", meaning: "life (daily living); livelihood" },
            { hanzi: "生产", pinyin: "shēng chǎn", meaning: "produce; production (manufacturing)" },
            { hanzi: "生日", pinyin: "shēng rì", meaning: "birthday" },
            { hanzi: "生病", pinyin: "shēng bìng", meaning: "get sick; be ill" },
            { hanzi: "陌生", pinyin: "mò shēng", meaning: "strange; unfamiliar" },
            { hanzi: "天生", pinyin: "tiān shēng", meaning: "born with; innate; by nature" },
            { hanzi: "生命贵在运动", pinyin: "shēng mìng guì zài yùn dòng", meaning: "life values exercise (saying: exercise is essential)" },
            { hanzi: "贵在坚持", pinyin: "guì zài jiān chí", meaning: "the key is persistence (value lies in sticking with it)" },
            { hanzi: "幸福", pinyin: "xìng fú", meaning: "happiness; a happy life (more lasting than 开心)" },
            { hanzi: "幸运", pinyin: "xìng yùn", meaning: "lucky; good fortune" },
            { hanzi: "好运", pinyin: "hǎo yùn", meaning: "good luck (often as wish/condition)" },
            { hanzi: "年轻", pinyin: "nián qīng", meaning: "young" },
            { hanzi: "年老", pinyin: "nián lǎo", meaning: "old; elderly (describes age)" },
            { hanzi: "看起来", pinyin: "kàn qǐ lái", meaning: "seem; look like (from appearance)" },
            { hanzi: "一首歌", pinyin: "yì shǒu gē", meaning: "a song (首 = measure word for songs/poems)" },
            { hanzi: "歌词", pinyin: "gē cí", meaning: "lyrics" },
            { hanzi: "瘦", pinyin: "shòu", meaning: "thin; slim" },
            { hanzi: "变瘦了", pinyin: "biàn shòu le", meaning: "got thinner" },
            { hanzi: "年纪", pinyin: "nián jì", meaning: "age (how old someone is)" },
            { hanzi: "年轻人", pinyin: "nián qīng rén", meaning: "young people" },
            { hanzi: "老年人", pinyin: "lǎo nián rén", meaning: "elderly people" },
            { hanzi: "幸亏", pinyin: "xìng kuī", meaning: "luckily; fortunately (relief after danger/problem)" },
            { hanzi: "茉莉花", pinyin: "mò lì huā", meaning: "jasmine (flower; also a well-known song name)" },
            { hanzi: "免费", pinyin: "miǎn fèi", meaning: "free of charge" },
            { hanzi: "加班费", pinyin: "jiā bān fèi", meaning: "overtime pay" },
            { hanzi: "心疼", pinyin: "xīn téng", meaning: "feel sorry for someone; feel heartache (because you care)" },
            { hanzi: "心疼你", pinyin: "xīn téng nǐ", meaning: "I feel sorry for you / it hurts me to see you suffer" },
            { hanzi: "中奖", pinyin: "zhòng jiǎng", meaning: "win a prize (e.g., lottery)" },
            { hanzi: "方便", pinyin: "fāng biàn", meaning: "convenient; also euphemism for “go to the toilet” (context)" },
            { hanzi: "有空", pinyin: "yǒu kòng", meaning: "have free time; be available" },
            { hanzi: "上厕所", pinyin: "shàng cè suǒ", meaning: "go to the toilet" },
            { hanzi: "洗手间", pinyin: "xǐ shǒu jiān", meaning: "restroom; bathroom (polite)" },
            { hanzi: "大小便", pinyin: "dà xiǎo biàn", meaning: "urination and defecation (formal/medical)" },
            { hanzi: "聊天吗", pinyin: "liáo tiān ma", meaning: "want to chat? / can we chat?" },
            { hanzi: "逛街", pinyin: "guàng jiē", meaning: "go shopping; stroll around stores" },
            { hanzi: "疯了", pinyin: "fēng le", meaning: "(1) went crazy; (2) ‘that’s insane!’ (colloquial)" },
            { hanzi: "疯狂", pinyin: "fēng kuáng", meaning: "crazy; frenzied" },
            { hanzi: "芬芳", pinyin: "fēn fāng", meaning: "fragrant (often for flowers/perfume; literary)" },
            { hanzi: "将来", pinyin: "jiāng lái", meaning: "in the future; someday" },
            { hanzi: "工作狂", pinyin: "gōng zuò kuáng", meaning: "workaholic" },
            { hanzi: "狂风暴雨", pinyin: "kuáng fēng bào yǔ", meaning: "violent wind and storm; also figurative ‘fierce situation’" },
            { hanzi: "游戏", pinyin: "yóu xì", meaning: "game" },
            { hanzi: "画家", pinyin: "huà jiā", meaning: "painter; artist" },
            { hanzi: "夸赞", pinyin: "kuā zàn", meaning: "praise; compliment (formal-ish)" },
            { hanzi: "夸夸我", pinyin: "kuā kuā wǒ", meaning: "compliment me a bit (cute/colloquial)" },
            { hanzi: "涨价", pinyin: "zhǎng jià", meaning: "prices go up; raise the price" },
            { hanzi: "降价", pinyin: "jiàng jià", meaning: "prices go down; reduce the price" },
            { hanzi: "老是", pinyin: "lǎo shì", meaning: "always (often complaining); repeatedly" },
            { hanzi: "总是", pinyin: "zǒng shì", meaning: "always; consistently" },
            { hanzi: "你总是迟到", pinyin: "nǐ zǒng shì chí dào", meaning: "you’re always late (complaint)" },
            { hanzi: "一天一夜", pinyin: "yì tiān yí yè", meaning: "a whole day and night" },
            { hanzi: "求人不如求己", pinyin: "qiú rén bù rú qiú jǐ", meaning: "better rely on yourself than on others (saying)" },
            { hanzi: "舞台", pinyin: "wǔ tái", meaning: "stage (performance); platform (figurative)" },
            { hanzi: "收银台", pinyin: "shōu yín tái", meaning: "checkout counter (cashier desk)" },
            { hanzi: "收银员", pinyin: "shōu yín yuán", meaning: "cashier" },
            { hanzi: "付款", pinyin: "fù kuǎn", meaning: "pay; make payment" },
            { hanzi: "一场梦", pinyin: "yì chǎng mèng", meaning: "a dream (as an experience; 场 = measure word for events)" },
            { hanzi: "人生就是一场梦", pinyin: "rén shēng jiù shì yì chǎng mèng", meaning: "life is just a dream (figurative saying)" },
            { hanzi: "市场", pinyin: "shì chǎng", meaning: "market" },
            { hanzi: "机场", pinyin: "jī chǎng", meaning: "airport" },
            { hanzi: "升降机", pinyin: "shēng jiàng jī", meaning: "elevator/lift (also: hoist; more formal term)" },
            { hanzi: "熬夜对身体不好", pinyin: "áo yè duì shēn tǐ bù hǎo", meaning: "staying up late is bad for your health" },
            { hanzi: "不要老加班", pinyin: "bú yào lǎo jiā bān", meaning: "don’t always work overtime" },
            { hanzi: "不得不说", pinyin: "bù dé bù shuō", meaning: "have to say; can’t help but say" },
            { hanzi: "打不得", pinyin: "dǎ bu dé", meaning: "can’t be hit; not to be scolded/criticized harshly (context)" },
            { hanzi: "吃得完", pinyin: "chī de wán", meaning: "be able to finish eating (quantity)" },
            { hanzi: "正好", pinyin: "zhèng hǎo", meaning: "just right; happens to (perfect timing)" },
            { hanzi: "紧张", pinyin: "jǐn zhāng", meaning: "nervous; tense" },
            { hanzi: "放松", pinyin: "fàng sōng", meaning: "relax" },
            { hanzi: "宠物", pinyin: "chǒng wù", meaning: "pet" },
            { hanzi: "电视剧", pinyin: "diàn shì jù", meaning: "TV series/drama" },
            { hanzi: "来的正是时候", pinyin: "lái de zhèng shì shí hou", meaning: "you came at just the right time" },
            { hanzi: "别紧张", pinyin: "bié jǐn zhāng", meaning: "don’t be nervous" },
            { hanzi: "放松一下", pinyin: "fàng sōng yí xià", meaning: "relax a bit" },
            { hanzi: "泡温泉", pinyin: "pào wēn quán", meaning: "soak in hot springs" },
            { hanzi: "泡面", pinyin: "pào miàn", meaning: "instant noodles (the kind you soak in hot water)" },
            { hanzi: "方便面", pinyin: "fāng biàn miàn", meaning: "instant noodles (common term)" },
            { hanzi: "走高速", pinyin: "zǒu gāo sù", meaning: "take the highway (drive via expressway)" },
            { hanzi: "高铁", pinyin: "gāo tiě", meaning: "high-speed rail" },
            { hanzi: "没毛病", pinyin: "méi máo bìng", meaning: "no problem; sounds good (slang approval)" },
            { hanzi: "美容院", pinyin: "měi róng yuàn", meaning: "beauty salon/spa" },
            { hanzi: "出汗", pinyin: "chū hàn", meaning: "sweat; perspire" },
            { hanzi: "精神", pinyin: "jīng shén", meaning: "(1) energetic; (2) spirit/mindset (context)" },
            { hanzi: "出了一身汗", pinyin: "chū le yì shēn hàn", meaning: "sweated all over" },
            { hanzi: "很精神", pinyin: "hěn jīng shén", meaning: "look energetic; in good spirits" },
            { hanzi: "喜欢是喜欢，不过不想买", pinyin: "xǐ huān shì xǐ huān, bú guò bù xiǎng mǎi", meaning: "I like it, but I don’t want to buy it (pattern: A is A, but…)" },
            { hanzi: "累是累，不过好开心", pinyin: "lèi shì lèi, bú guò hǎo kāi xīn", meaning: "I’m tired, but I’m really happy (contrast pattern)" },
            { hanzi: "便宜没好货", pinyin: "pián yi méi hǎo huò", meaning: "you get what you pay for (cheap stuff isn’t good) (saying)" },
            { hanzi: "去死吧", pinyin: "qù sǐ ba", meaning: "a harsh curse like “go to hell/die” (very rude; use with caution)" },
            { hanzi: "没什么大不了", pinyin: "méi shén me dà bù liǎo", meaning: "it’s no big deal" },
            { hanzi: "原谅", pinyin: "yuán liàng", meaning: "forgive" },
            { hanzi: "原谅别人，就是放过自己", pinyin: "yuán liàng bié rén, jiù shì fàng guò zì jǐ", meaning: "forgiving others is letting yourself go (saying)" },
            { hanzi: "别难过", pinyin: "bié nán guò", meaning: "don’t be sad" },
            { hanzi: "开心点儿", pinyin: "kāi xīn diǎn er", meaning: "cheer up; be a bit happier" },
            { hanzi: "分手", pinyin: "fēn shǒu", meaning: "break up (end a relationship)" },
            { hanzi: "大不了", pinyin: "dà bù liǎo", meaning: "worst case; at most (used to downplay consequences)" },
            { hanzi: "大不了我一个人过", pinyin: "dà bù liǎo wǒ yí ge rén guò", meaning: "worst case I’ll live on my own (I can manage alone)" },
            { hanzi: "吵架", pinyin: "chǎo jià", meaning: "argue; quarrel" },
            { hanzi: "打架", pinyin: "dǎ jià", meaning: "fight (physically)" },
            { hanzi: "痛并快乐着", pinyin: "tòng bìng kuài lè zhe", meaning: "painful but happy (a popular phrase for ‘tough yet enjoyable’)" },
            { hanzi: "凉快", pinyin: "liáng kuai", meaning: "cool (weather/temperature; comfortable cool)" },
            { hanzi: "痛快", pinyin: "tòng kuai", meaning: "really satisfying;爽快; also: ‘straightforward’" },
            { hanzi: "相爱一生", pinyin: "xiāng ài yì shēng", meaning: "love each other for a lifetime (romantic phrase)" },
            { hanzi: "你又加班，我很心疼你", pinyin: "nǐ yòu jiā bān, wǒ hěn xīn téng nǐ", meaning: "you’re working overtime again; I really feel for you" },
            { hanzi: "不着急", pinyin: "bú zháo jí", meaning: "no rush; don’t worry" },
            { hanzi: "骗人", pinyin: "piàn rén", meaning: "cheat/lie to someone; a liar (context)" },
            { hanzi: "骗自己", pinyin: "piàn zì jǐ", meaning: "lie to oneself; deceive oneself" },
            { hanzi: "哭一场", pinyin: "kū yì chǎng", meaning: "have a good cry (cry once thoroughly)" },
            { hanzi: "吃醋", pinyin: "chī cù", meaning: "be jealous (in romance)" },
            { hanzi: "一顿儿", pinyin: "yí dùnr", meaning: "a meal; one time of eating/scolding (colloquial; depends on verb)" },
            { hanzi: "挺好", pinyin: "tǐng hǎo", meaning: "pretty good" },
            { hanzi: "怪好看呢", pinyin: "guài hǎo kàn ne", meaning: "surprisingly good-looking (colloquial)" },
            { hanzi: "随便", pinyin: "suí biàn", meaning: "casual; as you like; not particular (also: sloppy/indifferent in attitude)" },
            { hanzi: "吓我一跳", pinyin: "xià wǒ yí tiào", meaning: "you startled me / gave me a fright" },
            { hanzi: "吓死我了", pinyin: "xià sǐ wǒ le", meaning: "scared me to death (exaggeration)" },
            { hanzi: "胸口", pinyin: "xiōng kǒu", meaning: "chest (the area around the heart)" },
            { hanzi: "很闷", pinyin: "hěn mèn", meaning: "feel tight/stuffy/oppressed (often about chest or mood)" },
            { hanzi: "穿衣", pinyin: "chuān yī", meaning: "to dress / to wear clothes" },
            { hanzi: "私家车", pinyin: "sī jiā chē", meaning: "private car (not a taxi/official vehicle)" },
            { hanzi: "私人物品", pinyin: "sī rén wù pǐn", meaning: "personal belongings" },
            { hanzi: "私事", pinyin: "sī shì", meaning: "private matter / personal business" },
            { hanzi: "本人", pinyin: "běn rén", meaning: "oneself; I/me (formal); the person in question" },
            { hanzi: "本地", pinyin: "běn dì", meaning: "local; this area" },
            { hanzi: "进口", pinyin: "jìn kǒu", meaning: "import (noun/verb)" },
            { hanzi: "出口", pinyin: "chū kǒu", meaning: "export (noun/verb); (also) exit" },
            { hanzi: "发霉了", pinyin: "fā méi le", meaning: "got moldy / has mildew" },
            { hanzi: "芒果干儿", pinyin: "máng guǒ gān er", meaning: "dried mango (colloquial with 儿)" },
            { hanzi: "干一行爱一行", pinyin: "gàn yì háng ài yì háng", meaning: "love the job you do; be devoted to your profession" },
            { hanzi: "同行", pinyin: "tóng háng", meaning: "people in the same profession;同行/peer" },
            { hanzi: "内行", pinyin: "nèi háng", meaning: "an expert; knowledgeable insider" },
            { hanzi: "外行", pinyin: "wài háng", meaning: "a layperson; not an expert" },
            { hanzi: "同事", pinyin: "tóng shì", meaning: "coworker/colleague" },
            { hanzi: "行业", pinyin: "háng yè", meaning: "industry; line of business" },
            { hanzi: "专利", pinyin: "zhuān lì", meaning: "patent" },
            { hanzi: "起床", pinyin: "qǐ chuáng", meaning: "get up (out of bed)" },
            { hanzi: "时差", pinyin: "shí chā", meaning: "time difference; jet lag" },
            { hanzi: "性别", pinyin: "xìng bié", meaning: "gender/sex (as a category)" },
            { hanzi: "办公室", pinyin: "bàn gōng shì", meaning: "office" },
            { hanzi: "会议室", pinyin: "huì yì shì", meaning: "meeting room/conference room" },
            { hanzi: "男朋友", pinyin: "nán péng you", meaning: "boyfriend" },
            { hanzi: "未婚", pinyin: "wèi hūn", meaning: "unmarried (never married)" },
            { hanzi: "已婚", pinyin: "yǐ hūn", meaning: "married" },
            { hanzi: "单身", pinyin: "dān shēn", meaning: "single (relationship status)" },
            { hanzi: "成家", pinyin: "chéng jiā", meaning: "to start a family; get married and settle down" },
            { hanzi: "幸运", pinyin: "xìng yùn", meaning: "lucky; good fortune" },
            { hanzi: "幸福", pinyin: "xìng fú", meaning: "happy;幸福/lasting well-being" },
            { hanzi: "幸亏", pinyin: "xìng kuī", meaning: "fortunately; luckily (it was that...)" },
            { hanzi: "千万", pinyin: "qiān wàn", meaning: "(1) by all means; must; (2) ten million (context-dependent)" },
            { hanzi: "彩票", pinyin: "cǎi piào", meaning: "lottery ticket" },
            { hanzi: "中奖", pinyin: "zhòng jiǎng", meaning: "to win a prize (lottery/contest)" },
            { hanzi: "奖金", pinyin: "jiǎng jīn", meaning: "prize money; bonus" },
            { hanzi: "妈妈说了我一顿", pinyin: "mā ma shuō le wǒ yí dùn", meaning: "Mom scolded me / gave me a telling-off" },
            { hanzi: "工资", pinyin: "gōng zī", meaning: "salary/wages" },
            { hanzi: "薪水", pinyin: "xīn shuǐ", meaning: "salary (more general/neutral term)" },
            { hanzi: "发工资", pinyin: "fā gōng zī", meaning: "to pay out salaries / payday" },
            { hanzi: "交生活费", pinyin: "jiāo shēng huó fèi", meaning: "to pay living expenses/board (e.g., give household money)" },
            { hanzi: "交朋友", pinyin: "jiāo péng you", meaning: "to make friends" },
            { hanzi: "抱歉", pinyin: "bào qiàn", meaning: "sorry;歉意/express apology (polite)" },
            { hanzi: "靠走道", pinyin: "kào zǒu dào", meaning: "by the aisle; aisle seat (e.g., on a plane/train)" },
            { hanzi: "填表", pinyin: "tián biǎo", meaning: "fill out a form" },
            { hanzi: "日程表", pinyin: "rì chéng biǎo", meaning: "schedule; itinerary" },
            { hanzi: "尽力", pinyin: "jìn lì", meaning: "to do one’s best; try hard" },
            { hanzi: "活该", pinyin: "huó gāi", meaning: "serve you right (you deserve it)" },
            { hanzi: "不该", pinyin: "bù gāi", meaning: "shouldn’t; not supposed to; (also polite) I’m sorry/I shouldn’t have..." },
            { hanzi: "招待会", pinyin: "zhāo dài huì", meaning: "reception (formal event)" },
            { hanzi: "要不然", pinyin: "yào bù rán", meaning: "otherwise; if not" },
            { hanzi: "推迟", pinyin: "tuī chí", meaning: "postpone; delay" },
            { hanzi: "参观", pinyin: "cān guān", meaning: "to visit/tour (a place, e.g., factory/museum)" },
            { hanzi: "提前", pinyin: "tí qián", meaning: "in advance; ahead of time" },
            { hanzi: "正点", pinyin: "zhèng diǎn", meaning: "on time; punctual (exact time)" },
            { hanzi: "晚点", pinyin: "wǎn diǎn", meaning: "late/delayed (train/flight); a bit later" },
            { hanzi: "深表歉意", pinyin: "shēn biǎo qiàn yì", meaning: "to express one’s sincere/deep apologies (very formal)" },
            { hanzi: "给您带来不便", pinyin: "gěi nín dài lái bù biàn", meaning: "to cause you inconvenience (polite/formal)" },
            { hanzi: "对不起", pinyin: "duì bu qǐ", meaning: "sorry; I apologize" },
            { hanzi: "一个半小时", pinyin: "yí gè bàn xiǎo shí", meaning: "one and a half hours" },
            { hanzi: "半小时", pinyin: "bàn xiǎo shí", meaning: "half an hour" },
            { hanzi: "劝", pinyin: "quàn", meaning: "to persuade; advise (often to stop/avoid something)" },
            { hanzi: "困", pinyin: "kùn", meaning: "sleepy; tired" },
            { hanzi: "发挥正常", pinyin: "fā huī zhèng cháng", meaning: "to perform normally (as expected)" },
            { hanzi: "发挥", pinyin: "fā huī", meaning: "to bring into play; to perform (skills/ability)" },
            { hanzi: "超常发挥", pinyin: "chāo cháng fā huī", meaning: "to perform beyond one’s usual level" },
            { hanzi: "指挥", pinyin: "zhǐ huī", meaning: "to command/direct; conductor (music) (context)" },
            { hanzi: "一天到晚", pinyin: "yì tiān dào wǎn", meaning: "all day long (often complaining)" },
            { hanzi: "不停地", pinyin: "bù tíng de", meaning: "nonstop; continuously" },
            { hanzi: "做家务", pinyin: "zuò jiā wù", meaning: "do housework" },
            { hanzi: "看上", pinyin: "kàn shàng", meaning: "to take a liking to; to fancy; choose (often romantic/selection)" },
            { hanzi: "看上你", pinyin: "kàn shàng nǐ", meaning: "to fancy you / take a liking to you" },
            { hanzi: "公主", pinyin: "gōng zhǔ", meaning: "princess" },
            { hanzi: "王子", pinyin: "wáng zǐ", meaning: "prince" },
            { hanzi: "保姆", pinyin: "bǎo mǔ", meaning: "nanny; domestic helper" },
            { hanzi: "保安", pinyin: "bǎo ān", meaning: "security guard" },
            { hanzi: "爆粗口", pinyin: "bào cū kǒu", meaning: "to swear / use profanity (suddenly/strongly)" },
            { hanzi: "放屁", pinyin: "fàng pì", meaning: "(1) to fart; (2) nonsense! (rude rejection)" },
            { hanzi: "取消", pinyin: "qǔ xiāo", meaning: "cancel; call off" },
            { hanzi: "这辈子", pinyin: "zhè bèi zi", meaning: "this lifetime" },
            { hanzi: "上辈子", pinyin: "shàng bèi zi", meaning: "a previous life (reincarnation); last life" },
            { hanzi: "下辈子", pinyin: "xià bèi zi", meaning: "the next life" },
            { hanzi: "遇见", pinyin: "yù jiàn", meaning: "to meet (often by chance; more literary/romantic)" },
            { hanzi: "遇到", pinyin: "yù dào", meaning: "to run into; encounter (people/things/problems)" },
            { hanzi: "偶遇", pinyin: "ǒu yù", meaning: "chance encounter; to bump into unexpectedly" },
            { hanzi: "天涯海角", pinyin: "tiān yá hǎi jiǎo", meaning: "the ends of the earth (very far away)" },
            { hanzi: "相依相伴", pinyin: "xiāng yī xiāng bàn", meaning: "to depend on and accompany each other; stay together through it all" },
            { hanzi: "青丝", pinyin: "qīng sī", meaning: "black hair (poetic; youth)" },
            { hanzi: "思念", pinyin: "sī niàn", meaning: "to miss; long for (someone)" },
            { hanzi: "染头发", pinyin: "rǎn tóu fa", meaning: "to dye one’s hair" },
            { hanzi: "愿意", pinyin: "yuàn yì", meaning: "to be willing; would like to" },
            { hanzi: "情话", pinyin: "qíng huà", meaning: "sweet talk; romantic words" },
            { hanzi: "情歌", pinyin: "qíng gē", meaning: "love song" },
            { hanzi: "你愿意嫁给我吗", pinyin: "nǐ yuàn yì jià gěi wǒ ma", meaning: "Will you marry me? (said to a woman)" },
            { hanzi: "你愿意娶我吗", pinyin: "nǐ yuàn yì qǔ wǒ ma", meaning: "Will you marry me? (said to a man; from woman’s perspective)" },
            { hanzi: "当天", pinyin: "dàng tiān", meaning: "that very day" },
            { hanzi: "当初", pinyin: "dāng chū", meaning: "back then; at the beginning; originally" },
            { hanzi: "当时", pinyin: "dāng shí", meaning: "at that time" },
            { hanzi: "说话算话", pinyin: "shuō huà suàn huà", meaning: "to keep one’s word; mean what one says" },
            { hanzi: "转身", pinyin: "zhuǎn shēn", meaning: "to turn around (one’s body); turn away" },
            { hanzi: "退下", pinyin: "tuì xià", meaning: "to withdraw/step back (formal; e.g., after being dismissed)" },
            { hanzi: "比划", pinyin: "bǐ hua", meaning: "to gesture/demonstrate with hand movements" },
            { hanzi: "泪如雨下", pinyin: "lèi rú yǔ xià", meaning: "tears pouring down like rain (crying hard)" },
            { hanzi: "我正好儿有空", pinyin: "wǒ zhèng hǎo er yǒu kòng", meaning: "I happen to be free (right now)" },
            { hanzi: "实话实说", pinyin: "shí huà shí shuō", meaning: "to tell it like it is; speak honestly" },
            { hanzi: "来一趟办公室", pinyin: "lái yí tàng bàn gōng shì", meaning: "come to the office (for a visit/errand)" },
            { hanzi: "人家的事与你无关", pinyin: "rén jiā de shì yǔ nǐ wú guān", meaning: "it’s none of your business / it has nothing to do with you" }
        ]
    },
    {
        id: 2,
        name: "New Words 2",
        words: [
            { hanzi: "评委", pinyin: "píng wěi", meaning: "judge (on a panel/competition)" },
            { hanzi: "入围", pinyin: "rù wéi", meaning: "to make the shortlist; be selected as a finalist" },
            { hanzi: "患难与共", pinyin: "huàn nàn yǔ gòng", meaning: "to share hardships together; stand together in adversity" },
            { hanzi: "爱护", pinyin: "ài hù", meaning: "to cherish and protect; take good care of" },
            { hanzi: "自杀", pinyin: "zì shā", meaning: "suicide; to take one’s own life" },
            { hanzi: "80后", pinyin: "bā líng hòu", meaning: "people born in the 1980s (post-80s generation)" },
            { hanzi: "情况", pinyin: "qíng kuàng", meaning: "situation; condition; what’s going on" },
            { hanzi: "讨论", pinyin: "tǎo lùn", meaning: "to discuss; discussion" },
            { hanzi: "如何", pinyin: "rú hé", meaning: "how; in what way" },
            { hanzi: "全民", pinyin: "quán mín", meaning: "the whole nation; all citizens" },
            { hanzi: "全家", pinyin: "quán jiā", meaning: "the whole family" },
            { hanzi: "全身", pinyin: "quán shēn", meaning: "the whole body" },
            { hanzi: "叫他出来", pinyin: "jiào tā chū lái", meaning: "tell him to come out / call him out (to come out)" },
            { hanzi: "几年如一日", pinyin: "jǐ nián rú yí rì", meaning: "for years, day in and day out (consistently)" },
            { hanzi: "从不抱怨", pinyin: "cóng bù bào yuàn", meaning: "never complain" },
            { hanzi: "好几年了", pinyin: "hǎo jǐ nián le", meaning: "it’s been quite a few years" },
            { hanzi: "照顾", pinyin: "zhào gù", meaning: "to take care of; look after" },
            { hanzi: "爱护别人", pinyin: "ài hù bié ren", meaning: "to care for others; treat others with consideration" },
            { hanzi: "理想", pinyin: "lǐ xiǎng", meaning: "ideal; aspiration; dream (goal in life)" },
            { hanzi: "点头", pinyin: "diǎn tóu", meaning: "to nod (in agreement)" },
            { hanzi: "从来没", pinyin: "cóng lái méi", meaning: "have never (ever)" },
            { hanzi: "一直讲", pinyin: "yì zhí jiǎng", meaning: "keep talking; talk nonstop" },
            { hanzi: "睡着", pinyin: "shuì zháo", meaning: "to fall asleep" },
            { hanzi: "靠走道", pinyin: "kào zǒu dào", meaning: "by the aisle; aisle seat" },
            { hanzi: "尽管", pinyin: "jǐn guǎn", meaning: "despite; although; feel free to (do it), don’t hesitate" },
            { hanzi: "靠窗", pinyin: "kào chuāng", meaning: "by the window; window seat" },
            { hanzi: "开口", pinyin: "kāi kǒu", meaning: "to open one’s mouth (to speak/ask); to start speaking" },
            { hanzi: "在家靠父母", pinyin: "zài jiā kào fù mǔ", meaning: "at home, rely on parents (saying)" },
            { hanzi: "出门靠朋友", pinyin: "chū mén kào péng you", meaning: "when out, rely on friends (saying)" },
            { hanzi: "靠海", pinyin: "kào hǎi", meaning: "near the sea; coastal" },
            { hanzi: "红脸", pinyin: "hóng liǎn", meaning: "to blush; face turns red (shy/angry/drunk)" },
            { hanzi: "喝醉", pinyin: "hē zuì", meaning: "to get drunk" },
            { hanzi: "难受", pinyin: "nán shòu", meaning: "to feel unwell; uncomfortable; upset" },
            { hanzi: "白酒", pinyin: "bái jiǔ", meaning: "Chinese spirits/baijiu (strong liquor)" },
            { hanzi: "红酒", pinyin: "hóng jiǔ", meaning: "red wine (also used for wine in general)" },
            { hanzi: "自由", pinyin: "zì yóu", meaning: "freedom; free (not restricted)" },
            { hanzi: "歪歪头", pinyin: "wāi wāi tóu", meaning: "tilt one’s head (a little)" },
            { hanzi: "小声", pinyin: "xiǎo shēng", meaning: "in a low voice; keep it down" },
            { hanzi: "轮轮到我了", pinyin: "lún dào wǒ le", meaning: "it’s my turn now (more standard: 轮到我了)" },
            { hanzi: "炒饭", pinyin: "chǎo fàn", meaning: "fried rice" },
            { hanzi: "炒菜", pinyin: "chǎo cài", meaning: "to stir-fry dishes; stir-fried dish (context)" },
            { hanzi: "炒青菜", pinyin: "chǎo qīng cài", meaning: "stir-fried greens/vegetables" },
            { hanzi: "发信息", pinyin: "fā xìn xī", meaning: "to send a message (text/WeChat etc.)" },
            { hanzi: "在路上", pinyin: "zài lù shàng", meaning: "on the way" },
            { hanzi: "强项", pinyin: "qiáng xiàng", meaning: "strong point; strength (what one is good at)" },
            { hanzi: "弱项", pinyin: "ruò xiàng", meaning: "weak point; weakness" },
            { hanzi: "游泳项目", pinyin: "yóu yǒng xiàng mù", meaning: "swimming event (in sports); swimming category" },
            { hanzi: "项目经理", pinyin: "xiàng mù jīng lǐ", meaning: "project manager" },
            { hanzi: "狗是公的还是母的", pinyin: "gǒu shì gōng de hái shì mǔ de", meaning: "is the dog male or female?" },
            { hanzi: "居然", pinyin: "jū rán", meaning: "unexpectedly; to one’s surprise" },
            { hanzi: "放弃", pinyin: "fàng qì", meaning: "to give up; abandon" },
            { hanzi: "影响", pinyin: "yǐng xiǎng", meaning: "to affect; influence; impact" },
            { hanzi: "完美", pinyin: "wán měi", meaning: "perfect; flawless" },
            { hanzi: "完人", pinyin: "wán rén", meaning: "a perfect person (often idealized/rare)" },
            { hanzi: "正确", pinyin: "zhèng què", meaning: "correct; right" },
            { hanzi: "杂志", pinyin: "zá zhì", meaning: "magazine" },
            { hanzi: "仍然", pinyin: "réng rán", meaning: "still; yet; nevertheless" },
            { hanzi: "究竟", pinyin: "jiū jìng", meaning: "after all; ultimately; (in questions) on earth/just what" },
            { hanzi: "睡着了", pinyin: "shuì zháo le", meaning: "fell asleep" },
            { hanzi: "小点声", pinyin: "xiǎo diǎn shēng", meaning: "keep it down a bit; speak more quietly" },
            { hanzi: "别出声", pinyin: "bié chū shēng", meaning: "don’t make a sound" },
            { hanzi: "男人的肩膀靠不住女人的浪漫", pinyin: "nán rén de jiān bǎng kào bu zhù nǚ rén de làng màn", meaning: "a man’s shoulder can’t support a woman’s romance (saying: romance needs more than relying on someone)" },
            { hanzi: "后半夜", pinyin: "hòu bàn yè", meaning: "the second half of the night (after midnight)" },
            { hanzi: "前半夜", pinyin: "qián bàn yè", meaning: "the first half of the night (before midnight)" },
            { hanzi: "眉毛", pinyin: "méi mao", meaning: "eyebrow" },
            { hanzi: "鸡胸肉", pinyin: "jī xiōng ròu", meaning: "chicken breast" },
            { hanzi: "伸懒腰", pinyin: "shēn lǎn yāo", meaning: "to stretch (after waking/sitting long)" },
            { hanzi: "扭腰", pinyin: "niǔ yāo", meaning: "to twist one’s waist; do waist twists" },
            { hanzi: "嗓子", pinyin: "sǎng zi", meaning: "throat/voice (as in hoarse throat)" },
            { hanzi: "建议", pinyin: "jiàn yì", meaning: "suggest; suggestion; advice" },
            { hanzi: "零食", pinyin: "líng shí", meaning: "snacks" },
            { hanzi: "主食", pinyin: "zhǔ shí", meaning: "staple food (rice, noodles, bread)" },
            { hanzi: "零钱", pinyin: "líng qián", meaning: "small change; coins/bills for small amounts" },
            { hanzi: "减肥", pinyin: "jiǎn féi", meaning: "to lose weight; diet/slim down" },
            { hanzi: "住院", pinyin: "zhù yuàn", meaning: "to be hospitalized; stay in hospital" },
            { hanzi: "肩", pinyin: "jiān", meaning: "shoulder" },
            { hanzi: "组织", pinyin: "zǔ zhī", meaning: "to organize; organization (group/institution)" },
            { hanzi: "谁组织你们去爬山", pinyin: "shuí zǔ zhī nǐ men qù pá shān", meaning: "who organized you to go hiking/climb the mountain?" },
            { hanzi: "艳遇", pinyin: "yàn yù", meaning: "romantic/sexual fling encountered by chance (often suggestive)" },
            { hanzi: "从头到尾", pinyin: "cóng tóu dào wěi", meaning: "from beginning to end" },
            { hanzi: "粗细", pinyin: "cū xì", meaning: "thickness; coarse vs. fine (e.g., lines/hair/noodles)" },
            { hanzi: "自信", pinyin: "zì xìn", meaning: "self-confident" },
            { hanzi: "自我", pinyin: "zì wǒ", meaning: "self; oneself; ego (context)" },
            { hanzi: "耐烦", pinyin: "nài fán", meaning: "patient; able to tolerate; (often in negative) impatient" },
            { hanzi: "吃惊", pinyin: "chī jīng", meaning: "to be surprised/shocked" },
            { hanzi: "定了闹钟", pinyin: "dìng le nào zhōng", meaning: "set an alarm" },
            { hanzi: "联系号码", pinyin: "lián xì hào mǎ", meaning: "contact number" },
            { hanzi: "邮箱是什么", pinyin: "yóu xiāng shì shén me", meaning: "what is your email address?" },
            { hanzi: "电邮是什么", pinyin: "diàn yóu shì shén me", meaning: "what is your email? (email address)" },
            { hanzi: "联系方式", pinyin: "lián xì fāng shì", meaning: "contact information" },
            { hanzi: "留言", pinyin: "liú yán", meaning: "leave a message; message (voicemail/comment)" },
            { hanzi: "支持", pinyin: "zhī chí", meaning: "to support; backing" },
            { hanzi: "请教", pinyin: "qǐng jiào", meaning: "to ask for advice/instruction (polite)" },
            { hanzi: "好久不见", pinyin: "hǎo jiǔ bú jiàn", meaning: "long time no see" },
            { hanzi: "怎么样", pinyin: "zěn me yàng", meaning: "how is it?; how about it?; what’s up?" },
            { hanzi: "出国", pinyin: "chū guó", meaning: "to go abroad" },
            { hanzi: "回国", pinyin: "huí guó", meaning: "to return to one’s country" },
            { hanzi: "保持联系", pinyin: "bǎo chí lián xì", meaning: "to keep in touch" },
            { hanzi: "聚会", pinyin: "jù huì", meaning: "get-together; party; gathering" },
            { hanzi: "家庭聚会", pinyin: "jiā tíng jù huì", meaning: "family gathering" },
            { hanzi: "帮了我大忙", pinyin: "bāng le wǒ dà máng", meaning: "helped me a lot / did me a huge favor" },
            { hanzi: "改天", pinyin: "gǎi tiān", meaning: "another day; some other time" },
            { hanzi: "健身房", pinyin: "jiàn shēn fáng", meaning: "gym; fitness center" },
            { hanzi: "早起", pinyin: "zǎo qǐ", meaning: "to get up early" },
            { hanzi: "梦想", pinyin: "mèng xiǎng", meaning: "dream; aspiration" },
            { hanzi: "网站", pinyin: "wǎng zhàn", meaning: "website" },
            { hanzi: "网址", pinyin: "wǎng zhǐ", meaning: "website address; URL" },
            { hanzi: "访问网页", pinyin: "fǎng wèn wǎng yè", meaning: "to visit/access a webpage" },
            { hanzi: "网页", pinyin: "wǎng yè", meaning: "webpage" },
            { hanzi: "刷新", pinyin: "shuā xīn", meaning: "refresh/reload (a page)" },
            { hanzi: "刷短视频", pinyin: "shuā duǎn shì pín", meaning: "scroll/watch short videos (doomscroll style)" },
            { hanzi: "网络断了", pinyin: "wǎng luò duàn le", meaning: "the network disconnected / internet is down" },
            { hanzi: "分享", pinyin: "fēn xiǎng", meaning: "to share" },
            { hanzi: "房地产", pinyin: "fáng dì chǎn", meaning: "real estate" },
            { hanzi: "到期", pinyin: "dào qī", meaning: "to expire; reach the due date" },
            { hanzi: "保质期", pinyin: "bǎo zhì qī", meaning: "shelf life; best-before period" },
            { hanzi: "期限", pinyin: "qī xiàn", meaning: "time limit; deadline; term" },
            { hanzi: "退出", pinyin: "tuì chū", meaning: "to exit; log out; withdraw" },
            { hanzi: "重新登录", pinyin: "chóng xīn dēng lù", meaning: "to log in again" },
            { hanzi: "信号不好", pinyin: "xìn hào bù hǎo", meaning: "poor signal/reception" },
            { hanzi: "网速太慢", pinyin: "wǎng sù tài màn", meaning: "internet speed is too slow" },
            { hanzi: "打不开网页", pinyin: "dǎ bù kāi wǎng yè", meaning: "can’t open the webpage" },
            { hanzi: "手机没电了", pinyin: "shǒu jī méi diàn le", meaning: "phone is out of battery" },
            { hanzi: "啥时候", pinyin: "shá shí hou", meaning: "when (colloquial)" },
            { hanzi: "显示屏", pinyin: "xiǎn shì píng", meaning: "display screen/monitor" },
            { hanzi: "黑屏", pinyin: "hēi píng", meaning: "black screen (screen goes blank)" },
            { hanzi: "没信号", pinyin: "méi xìn hào", meaning: "no signal" },
            { hanzi: "打不了电话", pinyin: "dǎ bù liǎo diàn huà", meaning: "can’t make a phone call" },
            { hanzi: "浪费时间", pinyin: "làng fèi shí jiān", meaning: "waste time" },
            { hanzi: "密码", pinyin: "mì mǎ", meaning: "password; code" },
            { hanzi: "哦，对了", pinyin: "ó, duì le", meaning: "oh, right / oh, by the way" },
            { hanzi: "在线", pinyin: "zài xiàn", meaning: "online (status); on the internet" },
            { hanzi: "上线", pinyin: "shàng xiàn", meaning: "to go online; (product) to launch/go live" },
            { hanzi: "下线", pinyin: "xià xiàn", meaning: "to go offline; log off; (product) be taken down" },
            { hanzi: "很闲", pinyin: "hěn xián", meaning: "not busy; have plenty of free time" },
            { hanzi: "他不听我的", pinyin: "tā bù tīng wǒ de", meaning: "he won’t listen to me / won’t take my advice" },
            { hanzi: "你听说过这个吗", pinyin: "nǐ tīng shuō guò zhè ge ma", meaning: "have you heard of this?" },
            { hanzi: "吸烟", pinyin: "xī yān", meaning: "to smoke (cigarettes); smoking" },
            { hanzi: "喝酒", pinyin: "hē jiǔ", meaning: "to drink alcohol" },
            { hanzi: "关注", pinyin: "guān zhù", meaning: "to follow (account); pay attention to" },
            { hanzi: "点赞", pinyin: "diǎn zàn", meaning: "to like (a post); give a thumbs-up" },
            { hanzi: "评论", pinyin: "píng lùn", meaning: "to comment; comment/review" },
            { hanzi: "连着上两节课", pinyin: "lián zhe shàng liǎng jié kè", meaning: "have two classes back-to-back" },
            { hanzi: "白说", pinyin: "bái shuō", meaning: "say it for nothing; wasted words" },
            { hanzi: "白等", pinyin: "bái děng", meaning: "wait for nothing; wait in vain" },
            { hanzi: "100%", pinyin: "bǎi fēn bǎi", meaning: "one hundred percent; completely" },
            { hanzi: "重口味", pinyin: "zhòng kǒu wèi", meaning: "strong/heavy flavor; (slang) intense tastes" },
            { hanzi: "摇头", pinyin: "yáo tóu", meaning: "to shake one’s head (disagree/deny)" },
            { hanzi: "静音", pinyin: "jìng yīn", meaning: "mute; silent mode" },
            { hanzi: "喝前摇一摇", pinyin: "hē qián yáo yì yáo", meaning: "shake it before drinking (instruction)" },
            { hanzi: "提醒", pinyin: "tí xǐng", meaning: "to remind; reminder" },
            { hanzi: "叫醒", pinyin: "jiào xǐng", meaning: "to wake someone up" },
            { hanzi: "拍照", pinyin: "pāi zhào", meaning: "to take photos" },
            { hanzi: "照相", pinyin: "zhào xiàng", meaning: "to take a picture (more traditional term)" },
            { hanzi: "镜头", pinyin: "jìng tóu", meaning: "camera lens; shot (film/TV)" },
            { hanzi: "你摄像镜头没打开", pinyin: "nǐ shè xiàng jìng tóu méi dǎ kāi", meaning: "your camera isn’t turned on (video call)" },
            { hanzi: "点菜", pinyin: "diǎn cài", meaning: "to order dishes" },
            { hanzi: "买单", pinyin: "mǎi dān", meaning: "to pay the bill (often in restaurants)" },
            { hanzi: "家常便饭", pinyin: "jiā cháng biàn fàn", meaning: "home-style everyday meal; nothing fancy (also: commonplace)" },
            { hanzi: "厨艺", pinyin: "chú yì", meaning: "cooking skills" },
            { hanzi: "过奖", pinyin: "guò jiǎng", meaning: "you flatter me (modest response to praise)" },
            { hanzi: "这部新电影", pinyin: "zhè bù xīn diàn yǐng", meaning: "this new movie/film" },
            { hanzi: "这辆车值得买", pinyin: "zhè liàng chē zhí dé mǎi", meaning: "this car is worth buying" },
            { hanzi: "你值得去试一试", pinyin: "nǐ zhí dé qù shì yí shì", meaning: "it’s worth you giving it a try" },
            { hanzi: "他很胖", pinyin: "tā hěn pàng", meaning: "he is overweight/fat" },
            { hanzi: "一天吃八顿饭", pinyin: "yì tiān chī bā dùn fàn", meaning: "eat eight meals a day (exaggeration)" },
            { hanzi: "连着两个周末都去爬山了", pinyin: "lián zhe liǎng gè zhōu mò dōu qù pá shān le", meaning: "went hiking both weekends in a row" },
            { hanzi: "试穿一下", pinyin: "shì chuān yí xià", meaning: "try it on (clothes)" },
            { hanzi: "试吃一下", pinyin: "shì chī yí xià", meaning: "have a taste sample; try eating a bit" },
            { hanzi: "菜市场", pinyin: "cài shì chǎng", meaning: "vegetable market / wet market" },
            { hanzi: "高手", pinyin: "gāo shǒu", meaning: "expert; master (high-level)" },
            { hanzi: "歌手", pinyin: "gē shǒu", meaning: "singer" },
            { hanzi: "新手", pinyin: "xīn shǒu", meaning: "newbie; beginner" },
            { hanzi: "老手", pinyin: "lǎo shǒu", meaning: "old hand; veteran; experienced person" },
            { hanzi: "双赢", pinyin: "shuāng yíng", meaning: "win-win" },
            { hanzi: "佩服", pinyin: "pèi fú", meaning: "to admire; be impressed (by skills/character)" },
            { hanzi: "房间号", pinyin: "fáng jiān hào", meaning: "room number" },
            { hanzi: "近期", pinyin: "jìn qī", meaning: "recently; in the near term" },
            { hanzi: "深呼吸", pinyin: "shēn hū xī", meaning: "take a deep breath" },
            { hanzi: "一口气爬到5楼", pinyin: "yì kǒu qì pá dào wǔ lóu", meaning: "climb up to the 5th floor in one go (without stopping)" },
            { hanzi: "老什么呀，说不上", pinyin: "lǎo shén me ya, shuō bu shàng", meaning: "not old at all / I wouldn’t call it old (downplaying)" },
            { hanzi: "厨房", pinyin: "chú fáng", meaning: "kitchen" },
            { hanzi: "厨师", pinyin: "chú shī", meaning: "chef; cook" },
            { hanzi: "死记硬背", pinyin: "sǐ jì yìng bèi", meaning: "to memorize by rote; cram without understanding" },
            { hanzi: "休闲", pinyin: "xiū xián", meaning: "leisure; relaxing" },
            { hanzi: "下辈子", pinyin: "xià bèi zi", meaning: "the next life" },
            { hanzi: "黄赌毒", pinyin: "huáng dǔ dú", meaning: "pornography, gambling, and drugs (the ‘three evils’)" },
            { hanzi: "花心男人", pinyin: "huā xīn nán rén", meaning: "unfaithful/playboy-type man; philanderer" },
            { hanzi: "花花公子", pinyin: "huā huā gōng zǐ", meaning: "playboy; womanizer" },
            { hanzi: "今天很闲，不忙", pinyin: "jīn tiān hěn xián, bù máng", meaning: "I’m free today, not busy" },
            { hanzi: "很友好", pinyin: "hěn yǒu hǎo", meaning: "very friendly" },
            { hanzi: "认识", pinyin: "rèn shi", meaning: "to know (someone); to get acquainted" },
            { hanzi: "请客", pinyin: "qǐng kè", meaning: "to treat (pay for others’ food/drinks)" },
            { hanzi: "邀请", pinyin: "yāo qǐng", meaning: "to invite" },
            { hanzi: "咱俩", pinyin: "zán liǎ", meaning: "the two of us (inclusive, casual)" },
            { hanzi: "不好意思问", pinyin: "bù hǎo yì si wèn", meaning: "feel embarrassed to ask" },
            { hanzi: "不错", pinyin: "bù cuò", meaning: "not bad; pretty good" },
            { hanzi: "没错", pinyin: "méi cuò", meaning: "that’s right; correct" },
            { hanzi: "周末", pinyin: "zhōu mò", meaning: "weekend" },
            { hanzi: "未来", pinyin: "wèi lái", meaning: "the future" },
            { hanzi: "到底", pinyin: "dào dǐ", meaning: "after all; to the end; (in questions) on earth/what exactly" },
            { hanzi: "进步", pinyin: "jìn bù", meaning: "progress; improve" },
            { hanzi: "知道", pinyin: "zhī dào", meaning: "to know" },
            { hanzi: "我可以向您请教一个问题吗", pinyin: "wǒ kě yǐ xiàng nín qǐng jiào yí gè wèn tí ma", meaning: "may I ask you a question? (very polite)" },
            { hanzi: "求求人不如求己", pinyin: "qiú rén bù rú qiú jǐ", meaning: "it’s better to rely on yourself than to beg others" },
            { hanzi: "存钱罐", pinyin: "cún qián guàn", meaning: "piggy bank; money jar" },
            { hanzi: "小宝贝", pinyin: "xiǎo bǎo bèi", meaning: "sweetie; darling (affectionate)" },
            { hanzi: "小宝", pinyin: "xiǎo bǎo", meaning: "baby/sweetie (nickname)" },
            { hanzi: "我认识他，他不认识我", pinyin: "wǒ rèn shi tā, tā bù rèn shi wǒ", meaning: "I know who he is, but he doesn’t know me" },
            { hanzi: "我不吃辣的", pinyin: "wǒ bù chī là de", meaning: "I don’t eat spicy food" },
            { hanzi: "不吸烟", pinyin: "bù xī yān", meaning: "don’t smoke / non-smoker" },
            { hanzi: "你不要害怕，我来保护你", pinyin: "nǐ bú yào hài pà, wǒ lái bǎo hù nǐ", meaning: "don’t be afraid, I’ll protect you" },
            { hanzi: "发工资", pinyin: "fā gōng zī", meaning: "to pay out salaries / payday" },
            { hanzi: "存钱", pinyin: "cún qián", meaning: "to save money; deposit money" },
            { hanzi: "一部手机", pinyin: "yí bù shǒu jī", meaning: "a mobile phone (one unit)" },
            { hanzi: "存一部分钱", pinyin: "cún yí bù fèn qián", meaning: "save a portion of the money" },
            { hanzi: "趁着", pinyin: "chèn zhe", meaning: "to take advantage of (a time/opportunity while it lasts)" },
            { hanzi: "泡温泉", pinyin: "pào wēn quán", meaning: "soak in a hot spring" },
            { hanzi: "你别动", pinyin: "nǐ bié dòng", meaning: "don’t move" },
            { hanzi: "说话算话", pinyin: "shuō huà suàn huà", meaning: "to keep one’s word" },
            { hanzi: "你发言了没有", pinyin: "nǐ fā yán le méi yǒu", meaning: "did you speak (at the meeting)?" },
            { hanzi: "吃货", pinyin: "chī huò", meaning: "foodie; someone who loves eating" },
            { hanzi: "祝你好运", pinyin: "zhù nǐ hǎo yùn", meaning: "wish you good luck" },
            { hanzi: "零钱罐", pinyin: "líng qián guàn", meaning: "change jar; small-coin bank" },
            { hanzi: "招财猫", pinyin: "zhāo cái māo", meaning: "lucky cat/Maneki-neko (fortune-bringing cat figurine)" },
            { hanzi: "还不至于", pinyin: "hái bú zhì yú", meaning: "it’s not that bad; not to that extent" }
        ]
    },
    {
        id: 3,
        name: "New Words 3",
        words: [
            { hanzi: "赶时间", pinyin: "gǎn shí jiān", meaning: "in a hurry" },
            { hanzi: "转弯", pinyin: "zhuǎn wān", meaning: "turn a corner" },
            { hanzi: "后备箱", pinyin: "hòu bèi xiāng", meaning: "trunk" },
            { hanzi: "乘客", pinyin: "chéng kè", meaning: "passenger" },
            { hanzi: "尾号", pinyin: "wěi hào", meaning: "last digit (of a number)" },
            { hanzi: "竖一下", pinyin: "shù yī xià", meaning: "stand upright for a moment" },
            { hanzi: "系安全带", pinyin: "jì ān quán dài", meaning: "fasten the seat belt" },
            { hanzi: "系鞋带", pinyin: "jì xié dài", meaning: "tie shoelaces" },
            { hanzi: "拖鞋", pinyin: "tuō xié", meaning: "slipper" },
            { hanzi: "快迟到了", pinyin: "kuài chí dào le", meaning: "almost late" },
            { hanzi: "窗户", pinyin: "chuāng hù", meaning: "window" },
            { hanzi: "开玩笑", pinyin: "kāi wán xiào", meaning: "joke" },
            { hanzi: "省钱", pinyin: "shěng qián", meaning: "save money" },
            { hanzi: "调时间", pinyin: "tiáo shí jiān", meaning: "adjust the time" },
            { hanzi: "请假", pinyin: "qǐng jià", meaning: "ask for leave" },
            { hanzi: "靠走道", pinyin: "kào zǒu dào", meaning: "by the aisle" },
            { hanzi: "靠边停", pinyin: "kào biān tíng", meaning: "pull over" },
            { hanzi: "因为", pinyin: "yīn wèi", meaning: "because" },
            { hanzi: "为了", pinyin: "wèi le", meaning: "for the sake of" },
            { hanzi: "鞋带松了", pinyin: "xié dài sōng le", meaning: "shoelaces are loose" },
            { hanzi: "系领带", pinyin: "jì lǐng dài", meaning: "tie a tie" },
            { hanzi: "支付", pinyin: "zhī fù", meaning: "pay" },
            { hanzi: "网约车", pinyin: "wǎng yuē chē", meaning: "online-hailed car" },
            { hanzi: "约驾照", pinyin: "yuē jià zhào", meaning: "book a driving license test" },
            { hanzi: "无人驾驶", pinyin: "wú rén jià shǐ", meaning: "driverless" },
            { hanzi: "输入", pinyin: "shū rù", meaning: "input" },
            { hanzi: "点击", pinyin: "diǎn jī", meaning: "click" },
            { hanzi: "按键盘", pinyin: "àn jiàn pán", meaning: "press the keyboard" },
            { hanzi: "慢走", pinyin: "màn zǒu", meaning: "walk slowly" },
            { hanzi: "期待", pinyin: "qī dài", meaning: "look forward to" },
            { hanzi: "行程", pinyin: "xíng chéng", meaning: "itinerary" },
            { hanzi: "扫码", pinyin: "sǎo mǎ", meaning: "scan the code" },
            { hanzi: "花钱", pinyin: "huā qián", meaning: "spend money" },
            { hanzi: "长袖", pinyin: "cháng xiù", meaning: "long sleeves" },
            { hanzi: "短袖", pinyin: "duǎn xiù", meaning: "short sleeves" },
            { hanzi: "袖子", pinyin: "xiù zi", meaning: "sleeve" },
            { hanzi: "存钱", pinyin: "cún qián", meaning: "deposit money" },
            { hanzi: "来一趟", pinyin: "lái yí tàng", meaning: "come for a trip" },
            { hanzi: "这趟车", pinyin: "zhè tàng chē", meaning: "this trip by car" },
            { hanzi: "手提电脑", pinyin: "shǒu tí diàn nǎo", meaning: "laptop" },
            { hanzi: "白雪", pinyin: "bái xuě", meaning: "white snow" },
            { hanzi: "教学", pinyin: "jiào xué", meaning: "teaching" },
            { hanzi: "教", pinyin: "jiāo", meaning: "teach" },
            { hanzi: "出示登机牌", pinyin: "chū shì dēng jī pái", meaning: "show the boarding pass" },
            { hanzi: "航空公司", pinyin: "háng kōng gōng sī", meaning: "airline company" },
            { hanzi: "航班", pinyin: "háng bān", meaning: "flight" },
            { hanzi: "登机口", pinyin: "dēng jī kǒu", meaning: "boarding gate" },
            { hanzi: "旅途愉快", pinyin: "lǚ tú yú kuài", meaning: "have a pleasant trip" },
            { hanzi: "旅行", pinyin: "lǚ xíng", meaning: "travel" },
            { hanzi: "旅客", pinyin: "lǚ kè", meaning: "passenger" },
            { hanzi: "航站楼", pinyin: "háng zhàn lóu", meaning: "terminal building" },
            { hanzi: "小费", pinyin: "xiǎo fèi", meaning: "tip" },
            { hanzi: "找钱", pinyin: "zhǎo qián", meaning: "change money" },
            { hanzi: "休闲", pinyin: "xiū xián", meaning: "leisure" },
            { hanzi: "正式", pinyin: "zhèng shì", meaning: "formal" },
            { hanzi: "正点", pinyin: "zhèng diǎn", meaning: "on time" },
            { hanzi: "晚点", pinyin: "wǎn diǎn", meaning: "delayed" },
            { hanzi: "盖住", pinyin: "gài zhù", meaning: "cover" },
            { hanzi: "瓶盖", pinyin: "píng gài", meaning: "bottle cap" },
            { hanzi: "经济舱", pinyin: "jīng jì cāng", meaning: "economy class" },
            { hanzi: "商务舱", pinyin: "shāng wù cāng", meaning: "business class" },
            { hanzi: "头等舱", pinyin: "tóu děng cāng", meaning: "first class" },
            { hanzi: "闲人免进", pinyin: "xián rén miǎn jìn", meaning: "No Admittance" },
            { hanzi: "正中间", pinyin: "zhèng zhōng jiān", meaning: "right in the middle" },
            { hanzi: "迟到", pinyin: "chí dào", meaning: "late" },
            { hanzi: "厚脸皮", pinyin: "hòu liǎn pí", meaning: "thick-skinned" },
            { hanzi: "穿的很厚", pinyin: "chuān de hěn hòu", meaning: "wear very thick clothes" },
            { hanzi: "厚衣服", pinyin: "hòu yī fu", meaning: "thick clothes" },
            { hanzi: "录屏", pinyin: "lù píng", meaning: "screen recording" },
            { hanzi: "录音", pinyin: "lù yīn", meaning: "audio recording" },
            { hanzi: "录像", pinyin: "lù xiàng", meaning: "video recording" },
            { hanzi: "拍照", pinyin: "pāi zhào", meaning: "take photos" },
            { hanzi: "拍小视频", pinyin: "pāi xiǎo shì pín", meaning: "shoot short videos" },
            { hanzi: "少等", pinyin: "shǎo děng", meaning: "wait for a short time" },
            { hanzi: "少候", pinyin: "shǎo hòu", meaning: "wait a moment" },
            { hanzi: "盖上锅盖", pinyin: "gài shàng guō gài", meaning: "cover the pot lid" },
            { hanzi: "锅盖", pinyin: "guō gài", meaning: "pot lid" },
            { hanzi: "行李箱", pinyin: "xíng lǐ xiāng", meaning: "luggage" },
            { hanzi: "托运", pinyin: "tuō yùn", meaning: "check (luggage)" },
            { hanzi: "计划", pinyin: "jì huà", meaning: "plan" },
            { hanzi: "记录", pinyin: "jì lù", meaning: "record" },
            { hanzi: "入职手续", pinyin: "rù zhí shǒu xù", meaning: "onboarding procedures" },
            { hanzi: "入住手续", pinyin: "rù zhù shǒu xù", meaning: "check-in procedures" },
            { hanzi: "办手续", pinyin: "bàn shǒu xù", meaning: "go through procedures" },
            { hanzi: "候车厅", pinyin: "hòu chē tīng", meaning: "waiting room (for trains/buses)" },
            { hanzi: "候机厅", pinyin: "hòu jī tīng", meaning: "waiting room (for flights)" },
            { hanzi: "请等候", pinyin: "qǐng děng hòu", meaning: "please wait" },
            { hanzi: "拜托", pinyin: "bài tuō", meaning: "please" },
            { hanzi: "感恩节", pinyin: "Gǎn ēn jié", meaning: "Thanksgiving" },
            { hanzi: "过感恩节", pinyin: "guò Gǎn ēn jié", meaning: "celebrate Thanksgiving" },
            { hanzi: "安检", pinyin: "ān jiǎn", meaning: "security check" },
            { hanzi: "托盘", pinyin: "tuō pán", meaning: "tray" },
            { hanzi: "检票", pinyin: "jiǎn piào", meaning: "ticket check" },
            { hanzi: "体检", pinyin: "tǐ jiǎn", meaning: "physical examination" },
            { hanzi: "脱鞋子", pinyin: "tuō xié zi", meaning: "take off shoes" },
            { hanzi: "放心", pinyin: "fàng xīn", meaning: "rest assured" }
        ]
    }
];
